modal-labs/modal-examples

03_scaling_out/youtube_face_detection.py

In the future we could develop our own `<video>` component, but for now this clears the warnings.

Fix a11y warning on video element

---

misc/webcam.py

Was debugging latencies and I realized there's also some Torch dataset that gets downloaded that wasn't cached.
Seems a bit faster now

Enable Torch cache too

---

misc/batch_inference_using_huggingface.py

Should prevent this error failing a synthetic monitoring run again:
```
│                                                                              │
│   196 │   │   sys.argv[0] = mod_spec.origin                                  │
│ ❱ 197 │   return _run_code(code, main_globals, None,                         │
│   198 │   │   │   │   │    "__main__", mod_spec)                             │
│                                                                              │
│ /var/lang/lib/python3.9/runpy.py:87 in _run_code                             │
│                                                                              │
│    86 │   │   │   │   │      __spec__ = mod_spec)                            │
│ ❱  87 │   exec(code, run_globals) …
```

batch-inference: handle rare flakes in model load

---

misc/pymc_pmf.py

This just fixes one warning. The fix that stops the entire example app failing is made to `pymc_stub` in a PR to that code.

pymc: Fix warning and typo in pymc example

---

misc/covid_datasette.py

More example robustness work. I realized why this error occasionally occurs:
```
Traceback (most recent call last):
File "/pkg/modal/_container_entrypoint.py", line 248, in handle_input_exception
yield
File "/pkg/modal/_container_entrypoint.py", line 337, in call_function_sync
res = fun(*args, **kwargs)
File "/root/misc/covid_datasette.py", line 161, in prep_db
for i, batch in enumerate(chunks(records, size=batch_size)):
File "/root/misc/covid_datasette.py", line 140, in <lambda>
return iter(lambda: tuple(itertools.islice(it, size)), ())
File "/root/misc/covid_datasette.py", line 94, in load_daily_reports
yield from load_report(filepath)
File "/root/misc/covid_datasette.py", line 102, in load_report
for row in csv.DictReader(fp):
File "/usr/local/lib/python3.9/csv.py", line 111, in …
```

fix: Use an EFS (NFSv4) compatible locking mechanism on shared state mutations

---

misc/whisper_pod_transcriber/main.py
misc/whisper_pod_transcriber/web.py

Adds `start` and `end` annotations to all transcript segments, with links to the audio. It works really well!

whisper-demo: Add 'start-end' links to transcript segments

---

misc/whisper_pod_transcriber/whisper_frontend/src/index.css
misc/whisper_pod_transcriber/whisper_frontend/src/routes/episode.tsx

Adds a bit of Modal branding to the container count. 
You can maybe notice there's a little bit of jitter. I can't work out why exactly this is happening. Originally I had an animated rectangle _per running container_, but in this setup the jitter was really too irritating.
https://user-images.githubusercontent.com/12058921/196586685-7e882390-8b6a-40a5-90bd-2419aded1652.mov

whisper demo: 'XX containers running' glow up

---

04_secrets/db_to_sheet.py
05_scheduling/hackernews_alerts.py

To be merged when the reworked apps page is going live

Refer to /apps instead of /deployments

---

misc/whisper_pod_transcriber/whisper_frontend/src/components/HomeButton.tsx
misc/whisper_pod_transcriber/whisper_frontend/src/routes/episode.tsx
misc/whisper_pod_transcriber/whisper_frontend/src/routes/podcast.tsx

Was finding it a bit annoying to navigate back to search after transcribing an episode.

whisper: Add top-left home button for easier app navigation

---

.github/workflows/cd.yml
.github/workflows/check.yml

The current Python version used does not support built-ins as type annotations, so [my deploy script is failing](https://github.com/modal-labs/modal-examples/actions/runs/3395370990/jobs/5645167212).

Use Python 3.9 in Github Actions, as we do locally.

---

example_deploy.py

Deployment is failing in Github Actions and I can't see why. Making this change to _actually_ log what happened in the deploy 😖.
The stderr output is quite ugly right now because there's no way (that I know of) to turn of the fancy `rich` tracebacks. Those get mangled in the subprocess.

better debug on deploy fail

---

misc/whisper_pod_transcriber/whisper_frontend/src/app.tsx
misc/whisper_pod_transcriber/whisper_frontend/src/routes/episode.tsx

Better mobile styling on transcripts page.

Mobile friendly transcripts; fix URLs in front page

---

misc/whisper_pod_transcriber/api.py
misc/whisper_pod_transcriber/podcast.py
misc/whisper_pod_transcriber/whisper_frontend/src/routes/episode.tsx

* **Set a user agent**. Failing to download the audio with 403 is probably the most common error. I had someone message me about the demo not working and I'm betting this was the reason.
* **Handle errors in the UI**. Previously the UI would just get into a loop showing 0 containers running and never show the user that the transcription had failed. That's fixed now, and how it looks is shown below:
---
I don't offer a nice way for a user to proceed after getting an error, but this is good enough for now.

Improve reliability of whisper demo

---

ml/whisper_pod_transcriber/api.py
ml/whisper_pod_transcriber/main.py

We use a `modal.Dict` to avoid running multiple transcription jobs for the same podcast and provide a nice user experience on hard-refresh of the browser. _But_, we never expire the `Dict` values, and in the worst case this causes the following error: 
The input ID is presumably so old that its been deleted from DB.

fix: expire in-progress transcription jobs

---

06_gpu/stable_diffusion_cli.py

This adds an optimized Stable Diffusion 1.5 tutorial to our docs. The breakdown is:
- **A100**: 6.5s to load model and 1.6s per generation
- **T4**: 13s to load model and 3.7s per generation
One of the key changes is to use the pre-trained `diffusers.EulerAncestralDiscreteScheduler`. It is fast and generates high quality images with fewer steps (20-30). Other optimizations such as tracing are available [here](https://huggingface.co/docs/diffusers/optimization/fp16#memory-and-speed), so it may be possible to make the generation step faster.

Optimized Stable Diffusion 1.5 example with CLI

---

misc/dreambooth_app.py

It appears in Github Actions we can't create `interactive=True` functions and deploy, because this call fails when setting up the terminal: `old_settings = termios.tcgetattr(fd)`. 
You don't really want to deploy functions in interactive mode, so I've just turned it off. We should also emit a warning, or just refuse to deploy.
The traceback is garbled in Github Actions because our client doesn't support plaintext output, but you can recover the pretty-printed traceback by copying the garbled output and then printing it: `print(garbled.decode())`. 
<details closed>
<summary><strong>Traceback</strong></summary>
<br>
```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/modal/cli │
│ …
```

fix: turn off fn interactivity to fix app deploy github action

---

ml/text-to-pokemon/config.py
ml/text-to-pokemon/frontend/src/lib/components/Generator.svelte
ml/text-to-pokemon/frontend/src/lib/helpers/prefillPromptData.js
ml/text-to-pokemon/inpaint.py
ml/text-to-pokemon/main.py
ml/text-to-pokemon/utils.py

<kbd>
</kbd>
----
Pushing this example towards being 'showcase quality'.
* Fix progress bar 🐛 
* Better pre-filled prompts
* Cache final Pokémon card results, to avoid doing compositing every time on seen prompts
* New module `utils.py` for running operational tasks, such as purging the diskcache
* Replace the name on the Pokémon card ✨ (currently just hardcoded to Randomon)
* Pokémon card compositing is `.starmap`'d to parallelized. Will become more important as number of compositing steps increases.
**still todo**
* Better performance. It's still too slow, and could do with a 100% speedup. 
* New prompt → 40-60s
* Seen prompt → 5s
* Have some kind of function which maps prompts to Pokémon names. Can use simple mapping/transform rules, and fall back to random nonsense pseudo-Pokémon …

txt-to-pokemon polish

---

06_gpu/stable_diffusion_cli.py

* `cache_path` is provided twice, which seems unnecessary
* The floating point precision is already determined by the weights (running some benchmarks and removing this argument actually might even make it _faster_, although I'm not 100% sure)

removed superfluous arguments to from_pretrained

---

03_scaling_out/basic_grid_search.py

I noticed the model fits so fast that it doesn't really need many containers.
* Use a larger datasets
* Remove the `is_inside` stuff
It now actually maxes out at 70+ containers (and the script still takes only a few seconds). Nice!

Misc updates to basic grid search

---

06_gpu/import_torch.py

I noticed that we didn't have a minimal GPU example, and all the examples in the `06_gpu` folder were more complex programs, so I added a simple one with just the boilerplate.
If someone just wants to quickly run something on a GPU, I can link them this. Perhaps we could link the code from the https://modal.com/docs/guide/gpu page too?

Add a minimal PyTorch GPU example

---

.github/workflows/check.yml
06_gpu/stable_diffusion_cli.py
07_webhooks/count_faces.py
09_job_queues/doc_ocr_webapp.py
10_integrations/duckdb_nyc_taxi.py
example_mypy.py
pyproject.toml

Trying to pass the right combination of arguments and flags to get `mypy` working in a multi-project repo was too annoying, so knitting everything together in a Python script.
So far type-checking is only done on the 01-10 folders. I can't yet enable type-checking on the packages in misc, ml, and data because there are too many type issues. But can progressively fix those issues and then introduce `py.typed` marker files to opt-in packages to type-hint checking. 
**aside:** Why do we prefix the scripts with `example_`? Could we instead move scripts into a `scripts/` folder and remove the prefix?

mypy check script

---

09_job_queues/doc_ocr_webapp.py

Some old lint I just noticed when working on another, related doc.

fix: modal.aio_lookup isnt used in ex, and doesn't even exist

---

data/covid_datasette.py

Noticed this was broken just now when I went to test it. Consequences of not pinning package versions in our image definitions...

fix: updated datasette ver requires initialization step

---

10_integrations/duckdb_nyc_taxi.py

Use io.BytesIO's context manager to close the buffer after using it.

Use io.BytesIO context manager in duckdb example

---

ml/whisper_pod_transcriber/main.py

Still getting failure emails because I set 10 min timeout on `refresh_index` but not the fn it calls, `index()`. 😖

need longer timeout on index() fn

---

06_gpu/stable_diffusion_slackbot.py

Reverts modal-labs/modal-examples#129
I can't reproduce this 'missing paragraph' problem locally. Using `-` or `*` bullets both work. Possibly fixed by going back to 1 column layout, which happened 1 day after Akshat noticed the issue?  cc @aksh-at

Revert "Temp fix for Stable Diffusion Slackbot docs"

---

02_building_containers/import_sklearn.py

We're not using the current iteration of smoke tests, so this removes the annotation.

Remove smoke-test from import_sklearn

---

06_gpu_and_ml/stable_diffusion_cli.py

`diffusers` 0.10 integrated the Stable Diffusion pipeline with `safetensors`. I am adding that option here because it slightly reduces cold start speed (at best we gain ~1s). 
Measurements:
```
importing packages => 2.115561s
loading euler => 0.031964s
load pipe => 5.733712s
move_cuda => 3.039683s
total startup phase => 10.951955s
100%|██████████| 20/20 [00:04<00:00,  4.33it/s]
inference => 7.906272s
Sample 0 took 21.729s. Saving it to /tmp/stable-diffusion/output_0.png
100%|██████████| 20/20 [00:01<00:00, 18.41it/s]
inference => 1.219496s
Sample 1 took 1.770s. Saving it to /tmp/stable-diffusion/output_1.png
importing packages => 2.155115s
loading euler => 0.031708s
load pipe => 1.429608s
move_cuda => 5.361170s
total startup phase => 9.005111s
100%|██████████| 20/20 [00:05<00:00, …
```

Uses `safetensors` with `diffusers>=0.10`

---

06_gpu_and_ml/stable_diffusion_cli.py

Changing the example scheduler to use [DPMSolver++](https://huggingface.co/docs/diffusers/main/en/api/schedulers/multistep_dpm_solver) so we can generate images with 10 steps. With `batch_size=10` we can generate an image every 500ms on a A100. 
```shell
$ python 06_gpu_and_ml/stable_diffusion_cli.py "An 1600s oil painting of the New York City skyline" \
--batch-size 10
Sample 4 took 4.805s (0.481s / image).
Saving it to /tmp/stable-diffusion/output_0_4.png
Saving it to /tmp/stable-diffusion/output_1_4.png
Saving it to /tmp/stable-diffusion/output_2_4.png
Saving it to /tmp/stable-diffusion/output_3_4.png
Saving it to /tmp/stable-diffusion/output_4_4.png
Saving it to /tmp/stable-diffusion/output_5_4.png
Saving it to /tmp/stable-diffusion/output_6_4.png
Saving it to …
```

Changes scheduler to use DPMSolver++

---

06_gpu_and_ml/stable_diffusion_cli.py

This takes cold start time from 21s to 15s with no impact on inference time

remove torch.backends.cudnn.benchmark

---

06_gpu_and_ml/dreambooth_app.py

Updates the `train_dreambooth.py` script commit hash to include the fix in https://github.com/huggingface/diffusers/issues/1566. The way the training script reference is quite jank, let's see if we can do this better somehow (I checked and the training script is not distributed with the `diffusers` package unfortunately).

Fix dreambooth example

---

06_gpu_and_ml/whisper_pod_transcriber/main.py
06_gpu_and_ml/whisper_pod_transcriber/podcast.py
06_gpu_and_ml/whisper_pod_transcriber/whisper_frontend/src/app.tsx

I'm not yet going to do the work to actually support non-English transcription, but in the meantime this at least makes some effort to let user know that non-English is not supported.
<kbd>
</kbd>
---
(Also increases timeout for indexing cron function)

fix: show warning when podcast result is non-EN. addresses #166

---

06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/App.svelte
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/lib/components/CopyToClipboard.svelte
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/lib/components/Generator.svelte

Adds a share button below rendered cards to make it easier for users to show off their results. Intending for this feature to increase engagement when sharing the demo tomorrow.
If a `share` query param is present in the URL, the app immediately submits the param's prompt string and scrolls the cards into view. Shared prompts will typically be pre-rendered and cached, so results will be fast (~3-5s).

Text-to-Pokemon: share button

---

09_job_queues/doc_ocr_jobs.py

This PR updates small typo in `09_job_queues`

Chore: fix typo in documentation

---

06_gpu_and_ml/blender_video.py

**Ref:** https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1674846317345789
Could reproduce this user's issue locally by using `python3.7` instead of `python3.9`, which is what the example expects.
This is still a bit dubious because the Modal execution can be running a different Python version to the user's local machine, but this at least makes the example code not break.

Fix blender python version issue

---

example_test.py
example_utils.py

I think our example repo structure is straining under the limitation that all example files are only sourced one subdirectory deep. This PR extends the range of gathering to `1-2`. 
https://github.com/modal-labs/modal-examples/tree/main/06_gpu_and_ml is a good example of messiness that can be cleaned up. 
e.g  `06_gpu_and_ml/vision_model_training/assets` is `06_gpu_and_ml/vision_model_training.py` should be in one folder, but the latter couldn't be served in `docs/` if it was in a subdirectory. But also more generally, it'd be good if an example's code and its blog post image assets could be grouped into a subdirectory together.

Allow example files to be gathered from grandchild dirs

---

06_gpu_and_ml/tensorflow_tutorial.py

A TreeHacks hackathon team wanted to use Tensorflow and so grabbed this example code. Then, they unsurprisingly got stuck with some Conda problem when they tried to extend the image. 
Here I add a non-Conda 'Tensorflow with GPUs' image option.

provide a Conda-less Tensorflow GPU option in Tensorflow ex

---

06_gpu_and_ml/dreambooth_app.py

Per this issue https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1674169099238619
The `dreambooth_app.py` error with the message 
```
ERROR: Could not find a version that satisfies the requirement torchvision (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
```
Adding python version contraint fixes that.

Fix torchvision version error

---

10_integrations/algolia_indexer.py

It's unpleasant to add all these setup commands, but at least it works. `synchronicity` now requires at least `3.7.9`, and the container image only has `3.7.5`.

fix: the algolia container image py 3.7.5 is no longer acceptable to synchronicity

---

06_gpu_and_ml/webcam.py
07_webhooks/badges.py

`modal serve` doesn't run anything, but returns `0` exit code, so it looked like these examples were successful. 
From a quick look I don't see a consensus on whether a command like `modal serve`, which returns help info, should return `0` or non-zero. I looked at `git`, `cargo`, `rustup`, and `gh` and found a mix.

fix: 2 synmon serve cmd configs

---

06_gpu_and_ml/whisper_pod_transcriber/pod_transcriber/main.py
06_gpu_and_ml/whisper_streaming/main.py
07_webhooks/streaming.py
10_integrations/algolia_indexer.py

Basic example of using parallelizing Whisper transcription over CPU workers and streaming back the transcription segments as they complete. A couple of rough edges, but it works.
```
modal serve 06_gpu_and_ml/whisper_streaming/main.py
✓ Initialized. View app at https://modal.com/apps/ap-LSjEUamUOLvtgkqzqcYMZH
✓ Created objects.
├── 🔨 Created download_mp3_from_youtube.
├── 🔨 Created mount /home/ubuntu/modal-client
├── 🔨 Created mount /home/ubuntu/modal-examples/06_gpu_and_ml/whisper_streaming/main.py
├── 🔨 Created transcribe_segment.
├── 🔨 Created web => https://modal-labs--example-whisper-streaming-web-thundergolfer-dev.modal.run
└── 🔨 Created transcribe_cli.
️️⚡️ Serving... hit Ctrl-C to stop!
└──  Watching /home/ubuntu/modal-examples/06_gpu_and_ml/whisper_streaming.
⠧ Running app...
``` …

OpenAI whisper transcription streaming

---

06_gpu_and_ml/dreambooth_app.py

Should make the example faster, with no loss of useful functionality.

Dreambooth — Don't checkpoint at 500/600 steps; shallow clone repo at /root

---

07_web_endpoints/streaming.py

* Responding to https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1680620042163739.
* Iterable but an Iterator strikes again! https://twitter.com/jonobelotti_IO/status/1614106195866025985?s=20
cc @erikbern because this includes a `WarnIfGeneratorIsNotConsumer` gotcha:

Extend basic streaming example mod

---

06_gpu_and_ml/chatgpt/chatgpt_streaming.py

It's actually pretty cool how easy this is. 
---
I couldn't have a single Modal function because I got an error that a `@stub.web_endpoint` must return a streaming response while I needed the function to have a return type `Union[StreamingResponse, Iterable[str]]`. 
But being [able to call a Modal function as a standard Python function](https://github.com/modal-labs/modal-examples/compare/jonathon/chatgpt-streaming?expand=1#diff-6e8b58b0668dca39d184f38b455bcef5963f94f6854f40984242d41b293bcf01R67) came in handy so I still got nice code reuse :)
I'm going to link this example from our new streaming doc page (also just noticed a typo I need to fix 😖) — https://modal.com/docs/guide/streaming-endpoints.

ChatGPT streaming example

---

06_gpu_and_ml/obj_detection_webcam/webcam.py

Static files are already mounted, so this is unnecessary.

Remove unnecessary route in webcam example

---

01_getting_started/hello_world.py

Motivated by https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1681242971024609 I went looking for a place in our docs to add more about the `f()` vs `f.call()` distinction. 
> Aside: The log streaming was definitely more sluggish than it used to be. It used to be so snappy. 
cc @erikbern as this is a prominent example and you may have thoughts.

make 'hello world' ex clear about local/remote execution

---

06_gpu_and_ml/langchains/potus_speech_qanda.py

This example started failing a couple of days ago and I wasn't checking syn-mon carefully enough to notice it.  A user pointed it out in beta-testing: https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1681380968649189. 
Deployed v3 https://modal.com/apps/modal-labs/example-langchain-qanda.

fix: LangChain example code rot

---

06_gpu_and_ml/dreambooth/dreambooth_app.py

A simple workaround to avoid this, detailed information could be found in Issue #282.

Dreambooth - Config as a string when kicking off the stub function directly

---

.flake8
.github/workflows/check.yml
pyproject.toml

We’ve already done this in the other repos, and I just ran flake8 over the repo and it’s sooo slow compared to ruff.
Part of proposed changes in **modal-examples repo tune-up** document.

Switch from flake8 to ruff

---

06_gpu_and_ml/stable_lm/main.py
06_gpu_and_ml/stable_lm/requirements.txt

Initial demo of running zero-shot text generation with Stability AI's [stablelm-tuned-alpha-7b](https://huggingface.co/stabilityai/stablelm-tuned-alpha-7b). Converted model checkpoints to `safetensors` format and used `accelerate` to manage device mapping for faster container load times.
Inspired by Modal's [alpaca_lora](https://github.com/modal-labs/modal-examples/blob/e994cd6f8411232f49b9485aa8fdb0fc3114047c/06_gpu_and_ml/alpaca/alpaca_lora.py) example.

initial demo of stable lm

---

06_gpu_and_ml/stable_lm/main.py

Fixes parsing error breaking our FE builds. We still need to write more notes on how to use this example, but restricting this addition to just fixing the code snippet to prevent a parsing error.

Fixes parsing error

---

.github/workflows/check.yml
11_notebooks/basic.ipynb
11_notebooks/jupyter_inside_modal.py
README.md

Adds a new **11_notebooks** section with Jupyter Notebook related examples.
* Basic notebook example
* 'Jupyter inside Modal' example, requested here: https://modalbetatesters.slack.com/archives/C031Z7DBQFL/p1676872844882179?thread_ts=1676861135.011809&cid=C031Z7DBQFL
* Takes Akshat's work from https://gist.github.com/aksh-at/0cc3f1d8840b70f42732de274c804dc7
Next job is to write a guide. Even though there's still one or two rough edges in the notebooks experience, it's worth documenting it for our users. A good notebooks experience is important for model training and fine-tuning, because the people that do that stuff tend to feel at home in notebooks.

Notebooks examples

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_onnx.py

This adds an example of running Stable Diffusion inference using the ONNX runtime. Cold boot is larger than the PyTorch example, but the inference is a little faster (~900ms on a A10G).

Adds stable diffusion ONNX example

---

06_gpu_and_ml/openllama.py

New to Modal 🎉 and working / learning through the docs, ran into the OpenLLaMa example erroring:
- Moved to new 400B token preview, old ones are gone 🤷‍♂️
- Ran into `RuntimeError('Python 3.11+ not yet supported for torch.compile')`, so pinned 3.10 version for Image
Any questions / alterations / feedback let me know!

Fix OpenLLaMa example for latest weights

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_cli.py

Adds explicit torch-cu116 version install after xformers install, to ensure it works on A10G

Fix stable-diffusion-cli A10 incompatibility

---

06_gpu_and_ml/flan_t5/flan_t5_finetune.py

Otherwise the docs link would just be `/docs/guide/ex/finetune.md`

Rename flan t5 finetune example

---

06_gpu_and_ml/falcon_bitsandbytes.py
06_gpu_and_ml/falcon_gptq.py

A beta-tester was having trouble with Huggingface network `Read timed out` errors when downloading a huge model from the Huggingface Hub until he started using hf-transfer: https://modalbetatesters.slack.com/archives/C031Z7DBQFL/p1688597095761039?thread_ts=1688563661.016519&cid=C031Z7DBQFL
It sacrifices progress bars for increased throughput (and possibly better download reliability?)
If `hf-transfer` is still not reliable, this snippet can be used to retry the download: 
```python
def download_model():
import requests.exceptions
import transformers
from huggingface_hub import snapshot_download
from tenacity import Retrying, retry_if_exception_type, stop_after_attempt, wait_exponential
for attempt in Retrying(
reraise=True,
retry=retry_if_exception_type(requests.exceptions.ConnectionError) …
```

perf: Use hf-transfer to dl large Falcon models

---

.github/workflows/cd.yml
.github/workflows/check.yml
internal/utils.py

In Github Actions CI we have some stricter PyDantic validation enabled that is not happy that we in some places don't provide constructor arguments for `Optional` BaseModel fields.

fix: provide default 'None' on Optional fields

---

06_gpu_and_ml/openai_whisper/streaming/main.py

pytube fix is no longer needed

---

07_web_endpoints/chatbot_spa.py

Replace the NetworkFileSystem with an image build step, and make it run transformer inference on the GPU. Previously, it reserved a GPU but was actually running on the CPU — oops!
This example is pretty outdated since LLMs popped off last year, but I think it's still nice to have a small & very fast one.

Speed up chatbot_spa

---

02_building_containers/screenshot.py
06_gpu_and_ml/dreambooth/dreambooth_app.py
06_gpu_and_ml/falcon_bitsandbytes.py
06_gpu_and_ml/falcon_gptq.py
06_gpu_and_ml/openllama.py
06_gpu_and_ml/vision_model_training.py
06_gpu_and_ml/vllm_inference.py
10_integrations/dbt/modal_dbt.py
10_integrations/duckdb_nyc_taxi.py
10_integrations/meltano/meltano_modal.py
10_integrations/modal_tailscale.py

I removed these examples, which have been failing for a while, and it's not high-priority to maintain those integrations right now.
I also removed some old `integration-test: false` annotations.

Remove meltano and dbt from synmon

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_aitemplate.py

I updated a comment in the `stable_diffusion_aitemplate.py` file to correct it. Currently, when the command is currently pasted, it ends up with an incorrect JSON format error with curl.

Update documentation comment for stable_diffusion_aitemplate.py

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_onnx.py

This was breaking ever since July 1 due to some breaking change with Tianlei Wu's model weights `tlwu/stable-diffusion-v1-5`. I replaced it with the `runwayml` version and simplified the code, also updating it to use `optimum[onnxruntime-gpu]`.

Fix the stable diffusion ONNX example

---

09_job_queues/doc_ocr_jobs.py

Fix broken path seemingly introduced in https://github.com/modal-labs/modal-examples/pull/381

ocr: fix modal.Image#run_function ref path

---

06_gpu_and_ml/dreambooth/instance_example_urls.txt

We keep getting `requests.exceptions.HTTPError: 429 Client Error: Unknown Error for url: https://i.imgur.com/fkRYgv6.png` from Imgur when running this example.

fix: more reliable dreambooth ex

---

10_integrations/dbt/dbt_sqlite.py

This is still failing even after the last change, with:
```
✓ Initialized. View app at https://modal.com/apps/ap-fQIyzNfW1pB26LmUua28m8
✓ Created objects.
├── 🔨 Created dbt_cli.
├── 🔨 Created mount 
│   /var/task/modal-examples/10_integrations/dbt/sample_proj_sqlite
├── 🔨 Created mount /var/task/modal-examples/10_integrations/dbt/dbt_sqlite.py
└── 🔨 Created explore.
Traceback (most recent call last):
File "/pkg/modal/_container_entrypoint.py", line 324, in handle_user_exception
yield
File "/pkg/modal/_container_entrypoint.py", line 641, in main
imp_fun = import_function(container_args.function_def, ser_cls, ser_fun, container_args.serialized_params)
File "/pkg/modal/_container_entrypoint.py", line 555, in import_function
module = importlib.import_module(function_def.module_name)
File …
```

Fix dbt_sqlite monitor in examples

---

06_gpu_and_ml/flan_t5/flan_t5_finetune.py

Making the Flan T5 example complete training even in the event of multiple pre-emptions. Tested with https://github.com/modal-labs/modal-client/pull/812. 
Example completed run that had simulated preemptions every 20 minutes: https://modal.com/logs/ap-VKZKjrvnrvQRIBQh1ZoCYM. 
(Another run: https://modal.com/logs/ap-xieXQbbKddhyyY7bPxgyvU, which is ongoing at time of PR)
Also should ensure the openAI whisper finetune example is robust to preemption, but won't do that now as it's kinda time consuming to test this stuff.

preemption handling in finetune example

---

06_gpu_and_ml/mlc_inference.py

It doesn't work because it imports the curses library, which requires PTY support.

Disable mlc_inference.py in synmon

---

06_gpu_and_ml/openllama.py

Doesn't work on gvisor and deprecated anyway.

Stop using MIG on openllama.py ex

---

06_gpu_and_ml/blender/blender_video.py

There's an undiagnosed problem with running this code on A100s. T4 always works fine.

fix: A100s not working 100% on blender_video example

---

07_web_endpoints/streaming.py

https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1694721024992329?thread_ts=1694719940.675039&cid=C031Z7H15DG

fix: modal.exception.InvalidError in streaming example

---

06_gpu_and_ml/dreambooth/dreambooth_app.py
06_gpu_and_ml/falcon_bitsandbytes.py
06_gpu_and_ml/falcon_gptq.py
06_gpu_and_ml/openllama.py

Reverts modal-labs/modal-examples#451

Revert "Pause running A100 examples on gvisor"

---

06_gpu_and_ml/vllm_inference.py

From a brief glance, the [recent addition of check_disk_space](https://github.com/huggingface/huggingface_hub/pull/1590) in `snapshot_download` broke things so that `snapshot_download` no longer creates the directory if it doesn't exist. This is because check disk space runs before that can happen. 
This explicitly creates the dir to fix.

fix vLLM example (make dirs)

---

06_gpu_and_ml/vllm_inference.py

Fixes #463. Pytorch 2.1.0 (https://github.com/pytorch/pytorch/releases/tag/v2.1.0) was just released just last week, and it's built using CUDA 12.1. The image we're using uses CUDA 11.8, as recommended by vLLM. Previously vLLM specified a dependency on torch>=2.0.0, and picked up this 2.1.0 version. That was pinned back to 2.0.1 in https://github.com/vllm-project/vllm/pull/1290. When picking up that SHA however, we ran into what https://github.com/vllm-project/vllm/pull/1239 fixes. So for now point to temporary fork with that fix.

Fix vLLM example

---

06_gpu_and_ml/text_generation_inference.py

If the latest version of a Huggingface model changes, then at runtime the transformers library will look for that version on disk and not find it because the diskcached files are for the old "revision".

Pin modal version in TGI example

---

06_gpu_and_ml/mlc_inference.py

Updates this example from ChatModule(model, lib_path) which will currently fail to run, to ChatModule(model, model_lib_path).  
The CUDA 12.1.0 image is deprecated/scheduled for deletion, so also ups to current 12.2.2.

Fix mlc_inference.py error in model_lib_path, upgrade to CUDA 12.2.2

---

02_building_containers/screenshot.py
06_gpu_and_ml/alpaca/alpaca_lora.py
09_job_queues/doc_ocr_jobs.py
10_integrations/dbt/dbt_sqlite.py
README.md

Recently we changed our example testing system to use Python 3.11. In future we should test examples for compatibility against multiple Python versions, but for now I've just added a disclaimer to the README.

Fix examples now that we test against Python 3.11

---

02_building_containers/import_sklearn.py
03_scaling_out/youtube_face_detection.py
06_gpu_and_ml/blender/blender_video.py
06_gpu_and_ml/stable_lm/main.py
07_web_endpoints/chatbot_spa.py
misc/news_summarizer.py

Turns out `is_inside` isn't widely used so I'm tempted to just deprecate it pretty soon

Change all is_inside to run_inside

---

06_gpu_and_ml/dreambooth/dreambooth_app.py
06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/spam-detect/spam_detect/app.py
06_gpu_and_ml/spam-detect/spam_detect/train.py
06_gpu_and_ml/tensorflow/tensorflow_tutorial.py
10_integrations/covid_datasette.py

Recent versions of the Modal client lets you work with volumes without attaching them to the stub

Don't assign volumes to stub

---

.github/workflows/check.yml
06_gpu_and_ml/vision_model_training.py

This is made redundant by Ruff.
Also updating CI to use Python 3.11, which is now standard here.

Remove isort from CI

---

06_gpu_and_ml/text_generation_inference.py

Without this a failure in the subprocess will not fail the build.

fix: error in download_model fn should fail build

---

10_integrations/streamlit/serve_streamlit.py

Updates Streamlit example to:
1. pin dependencies: avoids breaking example if dependencies update
2. installs missing dependency: `streamlit` now requires `git` to be installed
3. adds links to scripts: made it clearer that we need to create two scripts in order to run example

Update Streamlit example

---

10_integrations/streamlit/serve_streamlit.py

Python files are not copied when creating bundles, so adding a local link it was before will result in a 404.
I'm adding a Github link instead.

Adds GH URL to markdown

---

02_building_containers/import_sklearn.py
03_scaling_out/youtube_face_detection.py
06_gpu_and_ml/embeddings/text_embeddings_inference.py
07_web_endpoints/chatbot_spa.py

`run_inside` is pending deprecation

run_inside -> imports

---

06_gpu_and_ml/jsonformer/jsonformer_generate.py
06_gpu_and_ml/mlc_inference.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py
06_gpu_and_ml/text_generation_inference.py
06_gpu_and_ml/tgi_mixtral.py
06_gpu_and_ml/vllm_mixtral.py

Some of our examples build an image with a bunch of deps and then use it for both the ASGI app image and also the GPU container. Fixing it so it's only used for the latter. 
This was also misleading users into thinking they can only have one image for a stub.

Fix examples to use default image when sufficient

---

11_notebooks/jupyter_inside_modal.py

Replaces the use of Bore with a Modal Tunnel.

Updates example to use Modal Tunnel

---

06_gpu_and_ml/stable_diffusion/a1111_webui.py

This Git tag contains a fix for a dependency versioning issue introduced upstream by the stable-diffusion-webui authors on httpx 0.24.1. Bumping the tag fixes the issue.
Resolves #531.

Update A1111 example to 1.7.0

---

06_gpu_and_ml/flan_t5/flan_t5_finetune.py

Checkpointing without annoying callbacks: 
<kbd>
</kbd>
Can merge this when:

Use background commits in flan t5 finetune

---

06_gpu_and_ml/diffusers/train_and_serve_diffusers_script.py
06_gpu_and_ml/embeddings/text_embeddings_inference.py
06_gpu_and_ml/openai_whisper/finetuning/train/__main__.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_aitemplate.py
06_gpu_and_ml/text_generation_inference.py
06_gpu_and_ml/vllm_inference.py
10_integrations/pyjulia.py
10_integrations/stable_diffusion_slackbot.py

Already updated the secret source in our integration templates.

Change HUGGINGFACE_TOKEN to HF_TOKEN

---

06_gpu_and_ml/alpaca/alpaca_lora.py
06_gpu_and_ml/embeddings/instructor.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_cli.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_turbo.py

Using https://github.com/modal-labs/modal-client/pull/1136 for some examples.
This is just one or two lines less for most examples, but for `stable_diffusion_cli` it's a drastic reduction since we can use the same function for both `@build()` and `@enter()`

Example simplification using `@build`

---

06_gpu_and_ml/embeddings/wikipedia/download.py
06_gpu_and_ml/embeddings/wikipedia/main.py

Updates code to use new @build, @enter, @exit handlers

Update cls hooks

---

06_gpu_and_ml/embeddings/wikipedia/download.py

Looks like this doesn't work for `3.11`, we're investigating.

Pin Python and dep versions for embedding download

---

.github/workflows/check.yml
06_gpu_and_ml/openai_whisper/finetuning/train/__main__.py
06_gpu_and_ml/openai_whisper/finetuning/train/end_to_end_check.py
06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py
06_gpu_and_ml/spam-detect/spam_detect/app.py
06_gpu_and_ml/spam-detect/spam_detect/dataset.py
06_gpu_and_ml/spam-detect/spam_detect/model_registry.py
06_gpu_and_ml/spam-detect/spam_detect/model_storage.py
06_gpu_and_ml/spam-detect/spam_detect/models.py
06_gpu_and_ml/spam-detect/spam_detect/serving.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/inpaint.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/ops.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/pokemon_naming.py
10_integrations/covid_datasette.py
internal/typecheck.py
misc/news_summarizer.py

Seems like CI on modal-examples is breaking (see #566) because of the recent black 24.1.0 release, which is suddenly a lot stricter about formatting rules.
I'm pinning the black version to 23.11 so we don't have any more surprises in the future.

Fix CI and pin black version

---

06_gpu_and_ml/vllm_mixtral.py

Just fixing some small typos I spotted while walking through the guide!

Correct small typos in vllm_mixtral.py

---

04_secrets/db_to_sheet.py
05_scheduling/hackernews_alerts.py
06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
06_gpu_and_ml/embeddings/text_embeddings_inference.py
06_gpu_and_ml/embeddings/wikipedia/main.py
06_gpu_and_ml/mini_dalle_slackbot.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_aitemplate.py
06_gpu_and_ml/text_generation_inference.py
06_gpu_and_ml/vision_model_training.py
06_gpu_and_ml/vllm_inference.py
10_integrations/multion_news_agent.py
10_integrations/stable_diffusion_slackbot.py
misc/news_summarizer.py
misc/webscraper.py

Fixing usage of `secret=` which was recently deprecated in the client

Fix usage of deprecated secret= kwarg

---

06_gpu_and_ml/vllm_inference.py
06_gpu_and_ml/vllm_mixtral.py

Pin pytorch to previous version; latest version is causing issues with the nvidia cuda image.

pin pytorch

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py

Currently the deployed app fails because it fails to find FastAPI see https://github.com/modal-labs/modal-examples/issues/569

fix stable diffusion app

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_turbo.py

Pins the Python dependencies more tightly -- `~=0.x` means `~0.*` are all acceptable, so we want to pin `~=0.x.y`. Before `0`, it's SemVer-compliant to break on minor releases!

pin dependencies for sdxl turbo

---

06_gpu_and_ml/alpaca/alpaca_lora.py
06_gpu_and_ml/batch_inference/batch_inference_using_huggingface.py
06_gpu_and_ml/diffusers/train_and_serve_diffusers_script.py
06_gpu_and_ml/dreambooth/dreambooth_app.py
06_gpu_and_ml/embeddings/text_embeddings_inference.py
06_gpu_and_ml/embeddings/wikipedia/main.py
06_gpu_and_ml/falcon_bitsandbytes.py
06_gpu_and_ml/falcon_gptq.py
06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/openllama.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_cli.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_onnx.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_turbo.py
06_gpu_and_ml/stable_lm/stable_lm.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py
06_gpu_and_ml/text_generation_inference.py
06_gpu_and_ml/tgi_mixtral.py
06_gpu_and_ml/vision_model_training.py
06_gpu_and_ml/vllm_inference.py
06_gpu_and_ml/vllm_mixtral.py
07_web_endpoints/basic_web.py

We are deprecating the dunder hooks for lifecycle management (`__enter__`, `__exit__`, etc.) in favor of function decorators (`@enter`, `@exit`, etc.). See [the docs](https://modal.com/docs/guide/lifecycle-functions) for more details. This PR updates all deprecated code in the examples.

Convert examples to all use lifecycle method decorators

---

06_gpu_and_ml/embeddings/text_embeddings_inference.py
06_gpu_and_ml/embeddings/wikipedia/main.py
06_gpu_and_ml/llm-serving/text_generation_inference.py
06_gpu_and_ml/llm-serving/tgi_mixtral.py

This is now deprecated (and never actually worked)

Remove parameters from functions decorated with `@exit`

---

11_notebooks/basic.ipynb
11_notebooks/jupyter_inside_modal.py

Things have improved since these were last updated :)

refresh Jupyter Notebook examples

---

06_gpu_and_ml/outlines/outlines_generate.py

Add outlines example (restrict LLM outputs to a certain format) to modal-examples

Add outlines example to modal-examples

---

06_gpu_and_ml/llm-serving/text_generation_inference.py

After refactor, llm-frontend and llm-serving are in the same parent directory

Fix path for llm-frontend reference in tgi.py

---

06_gpu_and_ml/vision_model_training.py

`vision_model_training.py` has been red in CI for deployment for the last two commits.
Not entirely sure what the change was -- possibly in an upstream dependency? -- but with these changes (plus a small tweak to the secrets) it was deployable with `modal deploy` in main and in the synmon environment.

tighten dependencies, update name of wandb secret

---

.github/workflows/check.yml
.github/workflows/typecheck.yml

I love a good type system, but I'm not convinced of the value of the mypy type check.
Most of our examples break due to rotting from insufficiently-controlled dependencies, rather than anything detectable with types. Recall that the types of functions on Modal are often not even checkable locally. Furthermore, type hints in other Python libraries in the ML ecosystem are often poorly instrumented and so the checker is subject to false positives and negatives. And finally, we have other checks in place to ensure examples run end-to-end, so the most common user facing errors can be caught directly.
It is also about 4x slower than the other checks we run in CI,  >2min instead of ~30s, which IME pushes "waiting on a PR" into context switch territory.
But rather than fully removing the check, …

moves slow mypy type checking out of main check script

---

06_gpu_and_ml/llm-serving/falcon_bitsandbytes.py
06_gpu_and_ml/llm-serving/falcon_gptq.py
06_gpu_and_ml/llm-serving/openllama.py
06_gpu_and_ml/llm-serving/text_generation_inference.py
06_gpu_and_ml/llm-serving/tgi_mixtral.py
06_gpu_and_ml/llm-serving/vllm_gemma.py
06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/llm-serving/vllm_mixtral.py

- Updates the Docker containers used in several examples (`devel` versions that are easier to extend with fancy, bleeding-edge CUDA-dependent libraries; uses the latest versions from NVIDIA because they have a tight deprecation cycle)
- Boosts inference throughput by 2-3x for some examples by upgrading vLLM 🚀
- Handles shutdown of ray clusters in `@exit`
- Moves to full links to the Modal website, rather than relative, so that they are usable outside of the docs setting, e.g. clickable in VS Code

Improvements to LLM examples

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py

This example was calling a `webendpoint` with `.remote`, which is not possible.

fixes use in local_entrypoint, pins dependencies

---

.github/pull_request_template.md

Clarifies the use of some of the frontmatter fields, elaborates on the dependency-pinning practices.

Documents frontmatter fields and dependency pinning

---

06_gpu_and_ml/stable_diffusion/playground.py

Note that this example is still missing comments and explanations

adds local entrypoint for playground, matches infra with deployed version, pins deps

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_lightning.py

Like several other SD examples, there was no `modal run`-nable component, so synmon couldn't check for correctness. This PR adds in a local entrypoint and also applies some dependency pinning. Lastly, it changes the default prompt.

fixes monitoring of sdxl-lightning, pins deps, adds bicycling weasel

---

06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/openai_whisper/finetuning/train/end_to_end_check.py
07_web_endpoints/chatbot_spa.py

I'm preparing to deprecate `.new`
There _are_ some semi-legit use cases of it, but I think more generally it's not the case that you want to tie the lifecycle of any object to the lifecycle of an app – only sometimes. So I think we should resurrect the idea of ephemeral objects but in a slightly different way where you can just create them anywhere not associated with apps. But until then, the only valid use cases of `.new` are pretty fringe and you can easily get around it.

Remove a few use cases of .new

---

06_gpu_and_ml/chatgpt/chatgpt_streaming.py

fixes deprecated path for ChatGPT streaming example, makes modal run version cleaner

---

04_secrets/db_to_sheet.py

renames secrets, minor text fixes

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py
06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_lightning.py

Fix command example not working on Windows
By changing single-quotes to double-quotes

Fix command example not working on Windows

---

10_integrations/s3_bucket_mount.py

Borrows a pattern from the SDXL examples, and adds the relevant frontmatter to make the example actually work in synmon (I think)

moves the output file into /tmp, makes it work in synmon

---

06_gpu_and_ml/comfyui/comfy_ui.py

**User issue:** https://modal-com.slack.com/archives/C05TCR1B2UA/p1709558199272249
**Explanation of issue:**
This comfyUI issue is because the container gets EOF input on idle timeout but gets stuck here https://github.com/modal-labs/modal-client/blob/main/modal/_container_entrypoint.py#L396
This is a known issue where a container _with concurrent inputs enabled_ must wait for its inputs to finish before shutting down. In the case of this example I'd set the input timeout to 10 minutes, and an inputs is consistently getting stuck for 10 minutes (this is a separate possible bug to what I'm fixing here). 
Because the idle timeout is 60s, the input timeout is 10 minutes, and the container concurrency limit is **1**, the web app can get stuck unable to spin up a new container for **9 …

fix: ComfyUI stuck for 10mins issue

---

06_gpu_and_ml/comfyui/comfy_ui.py

Remove asgiproxy image dependency

---

06_gpu_and_ml/langchains/codelangchain/agent.py
06_gpu_and_ml/langchains/codelangchain/app.py
06_gpu_and_ml/langchains/codelangchain/common.py
06_gpu_and_ml/langchains/codelangchain/edges.py
06_gpu_and_ml/langchains/codelangchain/nodes.py
06_gpu_and_ml/langchains/codelangchain/retrieval.py
06_gpu_and_ml/langchains/codelangchain/sandbox.py
pyproject.toml

This example shows off the use of Sandboxes for securely executing code from LLMs and how to serve a LangServe application with `asgi_app`.
It comprises a LangGraph-defined agent that has access to the LangChain Expression Language docs and answers questions about LCEL by providing code samples. 

adds a langserve/langgraph example with code execution

---

06_gpu_and_ml/stable_diffusion/a1111_webui.py
06_gpu_and_ml/stable_diffusion/stable_video_diffusion.py
06_gpu_and_ml/tensorflow/tensorflow_tutorial.py
11_notebooks/jupyter_inside_modal.py
misc/queue_simple.py
pyproject.toml

updates examples to use new queue and nfs methods, closes #659

---

misc/queue_simple.py

Can't use ephemeral in global scope
We should fix ./11_notebooks/jupyter_inside_modal.py as well – will do that later

Fix queue_simple

---

.github/workflows/typecheck.yml
10_integrations/cloud_bucket_mount_loras.py
10_integrations/s3_bucket_mount.py
internal/typecheck.py

resolves a TODO and enables us to bring back typechecking without sacrificing latency of CI/CD on example PRs

parallelize typechecking so it runs faster, fix failing examples

---

02_building_containers/install_cuda.py
06_gpu_and_ml/openai_whisper/pod_transcriber/app/api.py
06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py
06_gpu_and_ml/stable_diffusion/a1111_webui.py
10_integrations/pyjulia.py
11_notebooks/jupyter_inside_modal.py

Noticed that this was red in the example synmon — it was a casualty of the `.new()` deprecation.
I also updated it to demonstrate `Volume` which we're trying to encourage everyone to adopt.
Funny enough we rolled out the new Volume viewer in the dashboard — which kind of obviates this example. We should think of a better hook for demonstrating the features here.
---
Additionally, there are a few bonus fixes for the `stub.<object>` deprecation that landed recently.

Fix Jupyter example

---

10_integrations/cloud_bucket_mount_loras.py

Hi, just fixing the link to GitHub, the repo name was wrong

Fix link to code in LoRAs example Gradio app

---

02_building_containers/screenshot.py

Updates the version of playwright that we install in the screenshot example for compatibility with Debian 12 (bookworm).

Update playwright version for debian 12 compat

---

06_gpu_and_ml/controlnet/controlnet_gradio_demos.py

Keep warm can easily lead to a budget getting consumed by an unknowing user who deploys this to play around with it and then forgets it.

Replace keep_warm with container_idle_timeout in example

---

06_gpu_and_ml/llm-serving/vllm_gemma.py

There was an error when I tried the example. Since my local python version was 3.12.2, ray package with version 2.10 was not supported throwing an error:
```
ERROR: Could not find a version that satisfies the requirement ray==2.10.0 (from versions: none)
ERROR: No matching distribution found for ray==2.10.0
```
I added a python version to the image to resolve this error. 
Example updates (Bug fixes, new features, etc.)

Add python version to the image to prevent pip install error

---

06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/llm-serving/vllm_mixtral.py

I've realized that the `ray==2.10.0` dependency only works with `python<=3.10`. Added `python_version="3.10"` to avoid `pip install` errors.

python_version in Image declaration

---

10_integrations/webscraper.py

the webscraper example is intermittently failing with 429s. the Slack SDK includes a rate limit retry handler, which this PR adds.
ran several scrapes simultaneously without error, so this should suffice, but will monitor.

adds rate limit handler from slack SDK

---

06_gpu_and_ml/llm-serving/vllm_gemma.py
06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/llm-serving/vllm_mixtral.py

- No need to add the EOS token for Mixtral since the tokenizer will handle it. Also, avoid adding a trailing space.
- Correct  `<start_of_turn>` token for Gemma and insert a line break as shown in the [chat template](https://huggingface.co/google/gemma-7b-it/blob/main/tokenizer_config.json#L1507)

Fix vLLM template

---

06_gpu_and_ml/embeddings/wikipedia/main.py

New base image version no longer has `numpy` pre-installed

Install numpy explicitly in wikipedia example

---

06_gpu_and_ml/blender/blender_video.py

> Each Blender release supports one Python version, and the package is only compatible with that version.
Just realized we should probably pin this dependency to avoid future breakage. Blender 4.1.0 happens to match Python 3.11.

Specify bpy / Blender 4.1.0

---

internal/run_example.py

we should only test examples that do not opt out of testing in the synthetic monitoring system

check for lambda-test flag in CI tests

---

06_gpu_and_ml/llm-serving/sgl_vlm.py

https://github.com/modal-labs/modal-examples/assets/10442975/dd621cf1-f665-4296-a316-cb0c539e8dd0

adds an example of SGLang running LLaVA-Next LLaMA 3 8B

---

06_gpu_and_ml/openai_whisper/pod_transcriber/app/api.py

Changes to the `get_call_graph` query broke the podcast transcriber example, which contained an assertion on the function name of one of the `InputInfo` nodes in the transcription call graph.

Fix podcast transcriber call graph root function name check

---

10_integrations/streamlit/serve_streamlit.py

set up testing of serve_streamlit, pin versions

---

10_integrations/pyjulia.py

This example [failed in CI recently](https://github.com/modal-labs/modal-examples/actions/runs/9474947842/job/26105482247). 
Pinning to the last known-working version of `pyjulia`, but I suspect this was actually just due to an out-of-date or otherwise invalid code cache (see error message in failed CI run).

pin pyjulia version, trigger rebuild

---

07_web_endpoints/basic_web.py

Expands the `basic_web` example, making use of the Swagger docs and walking carefully through the differences between GET/POST and query params and request bodies.

initial draft of basic_web with Swagger docs

---

06_gpu_and_ml/llm-serving/tgi_mixtral.py
06_gpu_and_ml/llm-serving/vllm_mixtral.py

These labels were accidentally removed in #704, breaking some existing links. (`tgi_app` has it's own label `llama3`, so it's not included in this PR)

Add web endpoint labels back

---

12_datasets/coco.py
12_datasets/rosettafold.py

Dunno why it took me so long to just do this. 
Successful and much faster runs on CoCo and RoseTTAFold with this added parallelization.

Dataset ingestion scripts update: parallelize ingest for RoseTTAFold, CoCo

---

10_integrations/pushgateway.py

This commit adds a cleanup step to the pushgateway application. This will make it so stale metrics don't hang around.

Clean up push gateway metrics on exit

---

10_integrations/pushgateway.py

Modal deploy is better fitted here because these are long-lived services which we want to have a consistent URL.

Change pushgateway deployment method to `modal deploy`

---

10_integrations/pushgateway.py

Previously, these were dead dev URLs. This commit publishes the real URLs so users can see the metrics for themselves.

Fix pushgateway public URLs

---

internal/readme.md

This commit add documentation for how our frontmatter interacts with example code.

Add documentation on testing frontmatter

---

06_gpu_and_ml/llm-serving/download_llama.py
06_gpu_and_ml/llm-serving/openai_compatible/client.py

fixes llama download for serving multiple models, adds more control to client for testing

---

06_gpu_and_ml/stable_diffusion/flux.py

thanks @Arro for the initial version!

add example for running flux

---

06_gpu_and_ml/stable_diffusion/flux.py

Stack the enter and build decorators for the flux example

---

06_gpu_and_ml/llm-serving/batched_whisper.py

Whisper with Dynamic Batching

---

06_gpu_and_ml/openai_whisper/batched_whisper.py

Change batched function param name to make batched output clearer

Change batch function param name for batched whisper example

---

03_scaling_out/dynamic_batching.py

Example for Dynamic Batching

---

06_gpu_and_ml/stable_diffusion/flux.py

Fix typo with flux example

---

07_web_endpoints/fasthtml_app.py

adds a very simple fastHTML example

---

.github/workflows/preview-docs.yml

It fails because there's no issue to comment on.
Could add conditional logic for posting but running the check is not necessary since the action is run on a merge commit already.

turn off preview docs on main

---

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py

The `inference` function saves the PIL image with format jpeg. The `web_inference` function sets an `image/jpeg` content type. The `main` cli entrypoint saves these *bytes* as a png. Doesn't actually matter in almost every case since file name isn't really used in python for inferring format, or in general. But this fixes it for clarity

FIX minor bug in stable_diffusion_xl.py

---

07_web_endpoints/fasthtml_app.py

Adds a 1-million-checkboxes style multiplayer checkbox game to show more complex example

expand fastHTML example to be a 10k checkboxes app

---

06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/hyperparameter-sweep/model.py

Some improvements, but still needs some more love fyi @ShariqM
- Re-organizes most of the training code. But the training is still pretty complex in a way that distracts from the core point. Maybe we want to separate those into modules we can import, like we do with the model?
- The logging of node info in messages is nice, but passing it around as `prepend_logs` is annoying and  made it hard to abstract the training code. I moved it into the `L.basicConfig` call because I couldn't find another way to handle it. But that config is global in the Python process, which means 1) when we call `train_model.remote` again to train the final model, we get that node's initial rank back and 2) we actually don't always end up with 8 nodes (if checkpoints are fast enough that containers get reused).
- …

partial rewrite of hp sweep example

---

06_gpu_and_ml/stable_diffusion/flux.py

can take 20 minutes or more -- and timeouts are shared between `enter` phase and main Function

adjust timeout for compilation of flux

---

06_gpu_and_ml/comfyui/comfyapp.py

~Basically adding parts of [this gist](https://gist.github.com/kramstrom/a3784d8246948db647e7e66df980d090) as further improvements to our comfy example. It does mainly two things:~
~- store model weights on a volume so that they can be re-used across different apps and allows you to change your image however you want it without having to re-download everything~
~- it changes the model downloading to use huggingface helpers instead which allows you to pass in a huggingface token and download protected models~
~Not sure if these fit best as inline code here or if the gist should be its own example / guide / blog post or scrapped completely and just remain as a gist.~
Updated the example instead to split up the image building steps into multiple & explain each step more thoroughly and how …

Update comfy example to emphasize how to iterate & avoid redownloading weights

---

10_integrations/tailscale/modal_tailscale.py

Updates Tailscale example to patch the Python socket library to use the Tailscale SOCKS5 proxy. This generalizes the example to other uses other than `requests`.

Update Tailscale example to use global SOCKS5 Proxy

---

06_gpu_and_ml/gpu_packing.py

Adds example with multiple model instances per container. 

GPU packing example

---

13_sandboxes/jupyter_sandbox.py

This PR adds a new sandbox example that shows how to spin up a Jupyter notebook in a sandbox.

Add jupyter notebook sandbox example

---

06_gpu_and_ml/llm-serving/download_llama.py
06_gpu_and_ml/llm-serving/openai_compatible/locustfile.py
06_gpu_and_ml/llm-serving/vllm_inference.py

The new w4a16 quants from Neural Magic are supported in vLLM and give us roughly the same performance and storage size for an 8B model as we had for a w8a8 quant of a 3B model.

switch to a higher param count, lower quant model

---

13_sandboxes/simple_code_interpreter.py

This PR adds a simple code interpreter sandbox example, showing how to use stdin and stdout for control of a process.

Add simple code interpreter sandbox example

---

06_gpu_and_ml/text-to-video/mochi.py

matches the default in Genmo's Gradio UI

boost num_inference_steps for better outputs

---

06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py

Adds a chat with RAG example using the following things:
- ColQwen2 to index the docs
- Qwen2-VL as a VLM
- Gradio chatUI and PDF upload UI
Some things I would do if I wanted people to actually use this in prod. Curious which of these people think is worth doing
- Optimize the cold start (takes 2 mins now on average)
- Optimize the inference time for the chat (currently ~10s). Would try vllm, but there's an issue with VLLM and the `transformers` version that `ColQwen2` needs, so I'd have to build vllm from source, which would increase build time?
- Try to make the app use less memory (I currently need an 80gb A100, largely because though the underlying model is the same, I couldn't find a clean way to use the same underlying object for the model, and so I end up having 2 model objects) …

Add ColQwen2 example

---

06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py

I edited the chatbot message history (and max tokens) to assist in my Peanut squirrel video

fixes to message ordering

---

13_sandboxes/simple_code_interpreter.py

Previously we had a bug in exec that made it drop some messages. This bug is fixed so we can return to our preferred exec pattern.

Return code interpreter example to use exec

---

06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
07_web_endpoints/chatbot_spa.py
10_integrations/cloud_bucket_mount_loras.py

Follow-up to https://github.com/modal-labs/modal-examples/pull/951. A few examples were still failing with the 2024.10 Image Builder because they had multiple images and imported `fastapi` in global scope, so the imports failed when running on the images without it.

Restructure multi-image examples to hide fastapi import

---

06_gpu_and_ml/text-to-pokemon/text_to_pokemon/config.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/lib/components/Callout.svelte
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/lib/components/PrefillPrompt.svelte
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py

This fixes some errors encountered in the `text-to-pokemon` example.
Pin `huggingface_hub` dependency to fix this dependency issue:
> ImportError("cannot import name 'cached_download' from 'huggingface_hub' ...)
Remove the deprecated `interactive=False` attribute:
> TypeError: _App.function() got an unexpected keyword argument 'interactive'
And some minor changes to the svelte code:
> [..] frontend/src/lib/components/PrefillPrompt.svelte:11:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
> [..] frontend/src/lib/components/Callout.svelte:43:4 Unused CSS selector ".callout p"

Fix errors in text-to-pokemon example

---

06_gpu_and_ml/torch_profiling.py

Move the `class Record` definition into the matmul loop -- it takes longer.
That was the original intent, cf. the text on optimization in "Improving the performance". I moved it out while measuring the difference and forgot to put it back.

moves class definition into loop, it's slower

---

13_sandboxes/codelangchain/agent.py
internal/utils.py

This will allow customization of Modal environment variables.
In this PR, I add `MODAL_AUTOMOUNT` for the `codelangchain/agent` example. I intend to use this to migrate the `MODAL_ENVIRONMENT` for examples incrementally.

enables environment variable configuration in frontmatter

---

06_gpu_and_ml/tensorflow/tensorflow_tutorial.py

This example runs on Python 3.8, which we're about to drop support for.
I picked an arbitrary "newer but not too new" version which we seem to be able to run the example to completion on. My depth of knowledge is shallow here though! The code doesn't crash and the loss goes down; what more can you ask for?

Bump the version of the tensorflow image in our tensorflow example

---

06_gpu_and_ml/comfyui/comfyapp.py
06_gpu_and_ml/comfyui/workflow_api.json

Addresses [this issue](https://github.com/modal-labs/modal-examples/issues/952) of the current example where the first build takes several minutes. This drives down the model downloading step to ~25s.
I also did a copy pass and tried to shorten explanation, especially the intro. I'd also like to do another pass in a next PR possibly combining UI / API into a single endpoint and replacing comfy run since [it's flaky](https://github.com/modal-labs/modal-examples/issues/861).

use volumes to download flux

---

.github/workflows/preview-docs.yml

We're updating from Node 18 to Node 22 LTS. Using the `.nvmrc` file to keep this step consistent and avoid having to change it in multiple places in the future.
This won't work until https://github.com/modal-labs/modal/pull/17482 is deployed.

Use the Node version specified in nvmrc to build

---

06_gpu_and_ml/text-to-video/mochi.py

Significantly cheaper inference, faster cold boots, and makes for a much more readable example.

Updates Mochi to use Diffusers

---

06_gpu_and_ml/llm-serving/trtllm_llama.py

Messed up my SI prefixes -- peta is _quadrillion_, not trillion.
For the record: the [H100 datasheet](https://resources.nvidia.com/en-us-tensor-core/nvidia-tensor-core-gpu-datasheet) from NVIDIA reports ~4 petaFLOPS "with sparsity". The rule of thumb is to cut in half for the much more typical dense case, cf Stas Bekman's ML Engineering notes.

stop slandering H100s

---

05_scheduling/hackernews_alerts.py
06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/llm-structured/jsonformer_generate.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/stable_diffusion/flux.py
06_gpu_and_ml/text-to-video/mochi.py
06_gpu_and_ml/yolo/finetune_yolo.py

- Update titles of some examples for SEO

Update examples titles for SEO

---

06_gpu_and_ml/comfyui/comfyapp.py
06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py
06_gpu_and_ml/llm-serving/sgl_vlm.py
06_gpu_and_ml/llm-serving/trtllm_llama.py
06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/stable_diffusion/text_to_image.py
07_web_endpoints/count_faces.py
07_web_endpoints/fasthtml-checkboxes/fasthtml_checkboxes.py
07_web_endpoints/fasthtml_app.py
10_integrations/streamlit/serve_streamlit.py

I got in the habit of adding this flag just so that there'd be a deployment available, but it doesn't meaningfully improve testing or monitoring in most cases and it clutters up our `main` environment.
A few small typo fixes are also included in this PR.

remove deployment from apps that don't need it

---

10_integrations/cloud_bucket_mount_loras.py

and also pin the Python version

resolve incompatibility issue between Gradio and Pydantic

---

05_scheduling/hackernews_alerts.py
06_gpu_and_ml/blender/blender_video.py
06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
06_gpu_and_ml/dreambooth/diffusers_lora_finetune.py
06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/langchains/potus_speech_qanda.py
06_gpu_and_ml/llm-serving/llama_cpp.py
06_gpu_and_ml/llm-serving/sgl_vlm.py
06_gpu_and_ml/llm-serving/trtllm_llama.py
06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/llm-structured/instructor_generate.py
06_gpu_and_ml/llm-structured/outlines_generate.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/stable_diffusion/flux.py
06_gpu_and_ml/stable_diffusion/image_to_image.py
06_gpu_and_ml/stable_diffusion/text_to_image.py
06_gpu_and_ml/tensorflow/tensorflow_tutorial.py
06_gpu_and_ml/yolo/finetune_yolo.py
09_job_queues/doc_ocr_jobs.py
10_integrations/cloud_bucket_mount_loras.py
10_integrations/covid_datasette.py
10_integrations/dbt/dbt_duckdb.py
10_integrations/s3_bucket_mount.py
13_sandboxes/codelangchain/agent.py
13_sandboxes/jupyter_sandbox.py
13_sandboxes/safe_code_execution.py
13_sandboxes/simple_code_interpreter.py

and removes a few stray `runtimes` tags that we don't need anymore, since all examples are run in `gvisor`.

removes unused 'tags' tag

---

05_scheduling/hackernews_alerts.py
06_gpu_and_ml/blender/blender_video.py
06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/llm-serving/sgl_vlm.py
06_gpu_and_ml/llm-structured/outlines_generate.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/stable_diffusion/flux.py
06_gpu_and_ml/tensorflow/tensorflow_tutorial.py
06_gpu_and_ml/yolo/finetune_yolo.py
09_job_queues/doc_ocr_jobs.py
10_integrations/cloud_bucket_mount_loras.py
10_integrations/covid_datasette.py
10_integrations/dbt/dbt_duckdb.py
10_integrations/s3_bucket_mount.py

This style looks cleaner to me -- it breaks up the long comments in a way that is visually similar to the effect of the whitespace once the contents are actually rendered.
I've been making this change piecemeal, as I update examples. I've been happy so far and so am editing some of our top examples (e.g. featured examples) to use this format.

write whitespace in markdown as blank lines, not empty comments

---

.github/workflows/cd.yml
12_datasets/imagenet.py
internal/deploy.py

and also check for the example's perferred environment (via the `env` tag)

change default modal environment for deployment

---

internal/deploy.py

That way we can set the default via an environment variable, but over-ride in the frontmatter.

prioritize metadata env over environment variables

---

06_gpu_and_ml/dreambooth/diffusers_lora_finetune.py
06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
09_job_queues/doc_ocr_webapp.py
10_integrations/streamlit/serve_streamlit.py

Small changes to text content or styling following up on #995

minor text fixes following removal of mounts

---

06_gpu_and_ml/blender/blender_video.py

at roughly the same cost (and still under a dollar), run the blender rendering in ~3 minutes instead of ~5 with the new L40S GPUs

speed up blender with L40S

---

06_gpu_and_ml/embeddings/wikipedia/main.py
06_gpu_and_ml/gpu_packing.py
06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/openai_whisper/batched_whisper.py
06_gpu_and_ml/sam/segment_anything.py
06_gpu_and_ml/stable_diffusion/flux.py
06_gpu_and_ml/stable_diffusion/image_to_image.py
06_gpu_and_ml/stable_diffusion/text_to_image.py
10_integrations/cloud_bucket_mount_loras.py
misc/trellis3d.py

Updating the examples to avoid using `@modal.build`.
I ended up using a few different patterns here. Most are oriented around mounting a `modal.Volume` at a location that aligns with the `HF_HUB_CACHE_DIR`. In some examples I added a separate target function for pre-caching the model, although I didn't do that everywhere. For a couple with smaller models, I just moved the `build` method to a standalone function passed to `Image.run_function`.

Migrate examples away from `@modal.build`

---

06_gpu_and_ml/llm-serving/sgl_vlm.py

Update SGLang example to use Qwen2-VL

---

06_gpu_and_ml/comfyui/comfyapp.py

The name of the third-party custom node changed, which broke the example; moving forward should consult [this registry](https://registry.comfy.org/nodes/pr-was-node-suite-comfyui-47064894) to find the correct name. Guessing it has to do with [introducing versioning](https://blog.comfy.org/p/launching-comfyui-registry) in the comfy registry
I also updated comfy-cli for good measure.

update custom node name

---

14_clusters/simple_torch_cluster_script.py

iiuc not necessary because our ops are all sync but good to include in case users take this code and run more complex scripts with it
cc @thecodingwizard

add barrier before process group cleanup

---

07_web_endpoints/discord_bot.py

The Bored API went down basically immediately after I published this example and has been hard down for a few days.
In searching for a more stable free public API, I uncovered the [🤯 Free Public API API](https://www.freepublicapis.com/api), which works well for our purposes.

switch to Free Public API API

---

06_gpu_and_ml/langchains/potus_speech_qanda.py

The 2022 State of the Union mysteriously disappeared from whitehouse.gov on January 20th, sometime between 11:20 am and 2:45 pm, maybe right around noon.
This PR points to a different transcript -- now featuring audience interjections! -- hosted by [UCSB's American Presidency Project](https://www.presidency.ucsb.edu).

pull the sotu transcript from UCSB

---

06_gpu_and_ml/llm-serving/vllm_inference.py
09_job_queues/doc_ocr_jobs.py
09_job_queues/doc_ocr_webapp.py
10_integrations/dbt_modal_inference/dbt_modal_inference.py

We're deprecating `.lookup` methods on Modal objects to streamline object creation. `.from_name` should now be the One Way To Do It. I have updated the examples accordingly. There were a couple cases where the examples demonstrated a pattern that couldn't be solved with a simple name substitution and required explicitly hydrating the object.
Part of CLI-96

Migrate object lookups in example scripts

---

13_sandboxes/codelangchain/agent.py

This example is failing in monitoring in a way that I can't replicate in any other environment. I suspect it's because we have automount turned on.
That's actually not necessary, since the contents of `./src` are pulled up without it. When we run in "module mode", i.e. with `modal run 13_sandboxes.codelangchain.agent`, we pull up the everything from `13_sandboxes` onto the image in `/root`.
I wasn't able to reconstruct _why_ we added explicit automounting here. It could be that client behavior there has changed and that's why it's no longer necessary?
I'm not positive that this will fix the failures, but they also aren't user-facing, so I'm pushing this up and waiting a bit to see what the synmon results show.

remove automount environment var in agent example

---

.pre-commit-config.yaml
05_scheduling/schedule_simple.py
06_gpu_and_ml/embeddings/wikipedia/download.py
06_gpu_and_ml/embeddings/wikipedia/main.py
06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/hyperparameter-sweep/src/dataset.py
06_gpu_and_ml/hyperparameter-sweep/src/model.py
06_gpu_and_ml/llm-serving/openai_compatible/client.py
06_gpu_and_ml/llm-serving/trtllm_llama.py
06_gpu_and_ml/openai_whisper/finetuning/train/end_to_end_check.py
06_gpu_and_ml/openai_whisper/finetuning/train/train.py
06_gpu_and_ml/sam/segment_anything.py
06_gpu_and_ml/stable_diffusion/text_to_image.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/inpaint.py
06_gpu_and_ml/text-to-pokemon/text_to_pokemon/ops.py
07_web_endpoints/count_faces.py
09_job_queues/doc_ocr_jobs.py
11_notebooks/basic.ipynb
12_datasets/coco.py
12_datasets/imagenet.py
12_datasets/laion400.py
12_datasets/rosettafold.py
internal/requirements.txt
internal/utils.py
misc/trellis3d.py

Our current version of ruff is outdated and is now giving warnings on VS Code extension due to the deprecation of ruff-lsp. I'm updating ruff now in all of our repositories.

Update from ruff v0.2.1 to ruff v0.9.6

---

06_gpu_and_ml/llm-serving/openai_compatible/client.py

We construct the web url using information about the vLLM deployment provided by the user or their Modal configuration, but we weren't looking at environments. That lead to a surprising error for @shariqm-modal when his client hit the deployment in the `main` environment of the `modal-labs` workspace, which had been deployed with proxy authorization.
I think there might be a better way to figure out URLs with the `.web_url` attribute of `Function`, but I'm not 100% sure how to handle `serve`, so pushing this fix instead.

update the vllm oai client script to accept/detect modal environments

---

06_gpu_and_ml/comfyui/comfyapp.py

Changed the node name again 🤷 
This time using semantic versioning as written about here: https://github.com/Comfy-Org/comfy-cli/issues/236

fix custom node

---

06_gpu_and_ml/llm-serving/vllm_inference.py

Updates and drastically simplifies vLLM example to use `@web_server` and spawn vLLM as a subprocess.
To test this: `modal serve` followed by `python 06_gpu_and_ml/llm-serving/openai_compatible/client.py --app example-vllm-openai-compatible --function serve-dev --api-key super-secret-key`

Simplify and revise vLLM example

---

.github/workflows/stale.yml

Copied over from the monorepo. This is helpful for making sure old branches don't get forgotten about or make the git clone size very large
(I went ahead and pruned all the stale branches on the examples repo manually before making this PR but then realized I should probably just automate it like I did on the monorepo.)

Add stale branch/pr gardening

---

06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/openai_whisper/finetuning/readme.md
06_gpu_and_ml/openai_whisper/pod_transcriber/README.md
06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py
06_gpu_and_ml/text-to-pokemon/README.md
07_web_endpoints/fasthtml-checkboxes/cbx_load_test.py
07_web_endpoints/fasthtml-checkboxes/fasthtml_checkboxes.py
13_sandboxes/codelangchain/agent.py
13_sandboxes/codelangchain/langserve.py
README.md

We're deprecating the automatic "module mode" execution of Python files from the modal CLI. This PR changes all the cases (that I could find via monitoring failures and a cutty regex) where we used that.

use the new -m flag where we're running 'module-style'

---

10_integrations/algolia_indexer.py

Omitting the change log entirely since it's all on one page and unclear how useful it is to users trying to search for something. For example if something matches in the changelog from last year is that even useful? 
Since it's all on one page users can just ctrl-f on that page to find something.

Update algolia_indexer.py to omit changelog

---

.github/workflows/build-and-run-example.yml

This PR uses the new [`MODAL_IGNORE_CACHE`](https://github.com/modal-labs/modal-client/pull/2891) flag to trigger image builds in CI without invalidating the cache for other applications in the same workspace, which blocked the actual use of the original implementation in #1074. Supercedes #1079.

updates image build CI

---

06_gpu_and_ml/comfyui/comfyapp.py
06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/langchains/potus_speech_qanda.py
06_gpu_and_ml/llm-serving/sgl_vlm.py
06_gpu_and_ml/llm-serving/trtllm_llama.py
06_gpu_and_ml/stable_diffusion/stable_video_diffusion.py
06_gpu_and_ml/stable_diffusion/text_to_image.py
07_web_endpoints/badges.py
07_web_endpoints/basic_web.py
07_web_endpoints/count_faces.py
07_web_endpoints/fastapi_app.py
07_web_endpoints/streaming.py
10_integrations/algolia_indexer.py
10_integrations/pushgateway.py
misc/falcon_bitsandbytes.py
misc/falcon_gptq.py
misc/stable_lm.py
misc/trellis3d.py

Updates the examples to be 1.0 compatible by substituting `modal.fastapi_endpoint` for `modal.web_endpoint`.
Needs to be merged before https://github.com/modal-labs/modal/pull/20457 as it fixes a cross-reference that needs to change.
Part of CLI-339

Migrate modal.web_endpoint to modal.fastapi_endpoint

---

misc/hello_shebang.py

feat: Add a shebang example which explains enable_output and app_run.

---

01_getting_started/hello_world.py
02_building_containers/screenshot.py
03_scaling_out/dynamic_batching.py
05_scheduling/hackernews_alerts.py
06_gpu_and_ml/comfyui/comfyapp.py
06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/openai_whisper/batched_whisper.py
07_web_endpoints/badges.py
10_integrations/algolia_indexer.py
10_integrations/covid_datasette.py
10_integrations/multion_news_agent.py

This PR makes all relative URLs, which are implicitly to https://modal.com, explicitly global URLs. That makes the URLs easier to copy from an editor at the expense of making it harder to catch 404s.
It also standardizes some formatting choices, e.g. using blank lines in places where the rendered page will have vertical spacing, like between blocks and around headers.

make relative modal.com links global, standardize formatting

---

06_gpu_and_ml/image-to-video/frontend/index.html
06_gpu_and_ml/image-to-video/image_to_video.py

Image to Video Example using [Lightricks' LTX-Video model](https://huggingface.co/Lightricks/LTX-Video).
Example demonstrates how to run this model on Modal using a `local_entrypoint`, create an inference API using `fastapi_endpoint`, and serve a frontend using `asgi_app`. 
- [✅] New example
- [✅] Example is testable in synthetic monitoring system, or `lambda-test: false` is added to example frontmatter (`---`)
- [✅] Example is tested by executing with `modal run` or an alternative `cmd` is provided in the example frontmatter (e.g. `cmd: ["modal", "deploy"]`)
- [✅] Example is tested by running with no arguments or the `args` are provided in the example frontmatter (e.g. `args: ["--prompt", "Formula for room temperature superconductor:"]`
- [✅] Example is documented with comments …

Image to Video Example

---

02_building_containers/screenshot.py
06_gpu_and_ml/flan_t5/flan_t5_finetune.py
06_gpu_and_ml/gpu_packing.py
06_gpu_and_ml/import_torch.py
07_web_endpoints/flask_streaming.py
10_integrations/covid_datasette.py
10_integrations/dbt_modal_inference/dbt_modal_inference.py
10_integrations/s3_bucket_mount.py
11_notebooks/jupyter_inside_modal.py

I've left the Python version unpinned in a few examples that we actually test, since they are cases where we'd want the feature to work across Python versions, e.g. the flask/FastAPI serving examples. These examples also generally have the library versions unpinned for the same reason. They're more like canaries for library compatibility issues than are the other examples, which are closer to applications and so have tighter version pinning.

pin python version in more examples

---

internal/run_example.py

The [build-and-run-example workflow](https://github.com/modal-labs/modal-examples/actions/workflows/build-and-run-example.yml) was failing silently because we always returned 0 instead of the example's actual returncode. This PR returns the returncode.

surface failures from run_random_example

---

02_building_containers/install_flash_attn.py

Intentionally not pinning dependencies so that this example can be used to monitor for regressions in this pattern for building `flash-attn`.

add example for installing flash attention

---

06_gpu_and_ml/comfyui/comfyapp.py

So that those who clone / develop locally can actually click through

add back in absolute links

---

06_gpu_and_ml/stable_diffusion/flux.py

In latest Modal versions, bools are not converted to ints implicitly in modal.parameters.

update compile parameter

---

.github/actions/setup/action.yml
.github/workflows/build-and-run-example.yml
.github/workflows/cd.yml
.github/workflows/check.yml
.github/workflows/preview-docs.yml
.github/workflows/stale.yml
.github/workflows/typecheck.yml

Implements [SEC-48](https://linear.app/modal-labs/issue/SEC-48/pin-all-github-actions-that-we-use-to-a-specific-hash) for `modal-examples`.

pin all GitHub Actions by hash

---

06_gpu_and_ml/llm-serving/ollama.py

This commit adds an example of how to use Ollama on Modal.

Add an Ollama serving example

---

06_gpu_and_ml/llm-serving/ollama.py

This commit fixes a nonexistent CLI option that was put in the example.

Fix a mistake in ollama example related to cli

---

02_building_containers/install_flash_attn.py

Follow up to https://github.com/modal-labs/modal-examples/pull/1095. One can install `flash-attn` from their repo instead of building it in the image builder.

Uses prebuild wheel for flash-atten

---

06_gpu_and_ml/protein-folding/esm3.py

We switched from a "comment continuation" to two comments when we added the concurrent decorator in #1122.
I think a parallel structure "Gradio requires ..." and "Gradio can ..." is the right way to do it with two comments.

minor text fixes

---

misc/ollama_deployment.py

- Create a new Python script to deploy Ollama as a Modal web service.
- Set up a persistent volume for storing model weights.
- Implement a method to pull new models to the service.
- Configure automatic scaling down when not in use.

feat(ollama_deployment)🚀: Add Ollama deployment script for Modal service

---

06_gpu_and_ml/llm-serving/vllm_inference.py

The suggested 1.13.3 is incompatible with httpx 0.28.0 and higher. With Python 3.13.3, my `pip install openai==1.13.3` installed httpx 0.28.1. Then `python openai_compatible/client.py` failed with `TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`.
This is a bug in older versions of openai. It was first reported in https://github.com/openai/openai-python/issues/1902 and fixed in https://github.com/openai/openai-python/pull/1905
`pip install openai==1.76.0 && python openai_compatible/client.py` worked.

fix: use openai client 1.76.0 in vllm_inference.py

---

06_gpu_and_ml/llm-serving/openai_compatible/load_test.py

Right now running `modal run openai_compatible/load_test.py` as instructed on
https://modal.com/docs/examples/vllm_inference#testing-the-server fails with
`InvalidError: Image ENV variables must be strings. Invalid keys:
['MODAL_ENVIRONMENT']`.
This happens when `environment` is `None`. Users reading these docs may not
have configured a modal environment yet. This change uses an empty string as
the fallback which is consistent with
`06_gpu_and_ml/llm-serving/openai_compatible/client.py`.
```bash
$ modal run openai_compatible/load_test.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/dxia/src/github.com/modal-labs/modal-examples/06_gpu_and_ml/llm-serving/openai_compatible │
│ /load_test.py:18 in <module> …
```

fix: set default environment for local `load_test.py`

---

06_gpu_and_ml/llm-serving/openai_compatible/load_test.py

Upgrade `locust` in the image to 2.36.2 to fix `ValueError: StatsEntry.use_response_times_cache must be set to True` error. Reported in https://github.com/locustio/locust/issues/2908 and fixed in https://github.com/locustio/locust/commit/1954b26b7000ffe73a70a6dea99c3a33534bd988.
Otherwise `modal run openai_compatible/load_test.py` shows this error.
<details>
<summary>before</summary>
```
[2025-04-26 22:16:07,792] modal/INFO/locust.main: --run-time limit reached, shutting down
[2025-04-26 22:16:07,793] modal/INFO/locust.runners: Got quit message from master, shutting down...
[2025-04-26 22:16:07,793] modal/INFO/locust.runners: Got quit message from master, shutting down...
[2025-04-26 22:16:07,793] modal/INFO/locust.runners: Got quit message from master, shutting down...
[2025-04-26 …
```

fix: `openai_compatible/load_test.py` errors

---

internal/requirements.txt

A few of the examples `import fastapi` in the global scope, which is important for properly using the `fastapi_endpoint` decorator.
Would prefer to find a different way to solve this (e.g. via an `extra` dependency of `modal`) long-term, but this will prevent all tests from failing while we do so.

adds fastapi to the development requirements

---

06_gpu_and_ml/embeddings/qdrant.py
06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/image-to-video/image_to_video.py
06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py
06_gpu_and_ml/long-training.py
06_gpu_and_ml/openai_whisper/batched_whisper.py
06_gpu_and_ml/protein-folding/boltz1.py
06_gpu_and_ml/protein-folding/chai1.py
06_gpu_and_ml/protein-folding/esm3.py
06_gpu_and_ml/stable_diffusion/text_to_image.py
06_gpu_and_ml/text-to-audio/musicgen.py
06_gpu_and_ml/torch_profiling.py
09_job_queues/doc_ocr_jobs.py
misc/deepseek_openai_server.py
misc/falcon_bitsandbytes.py

As pointed out by @davidxia in #1146, `Optional` is in fact supported by `typer` for CLIs.
This PR updates all of the places where we used `str = None` and `int = None` to express Optionals of those types. A quick-and-dirty grep didn't reveal any other types with this pattern.

properly type Optionals in args of Modal Functions/local entrypoints

---

06_gpu_and_ml/llm-serving/sgl_vlm.py

User may not have `requests` installed.
Fix some type checks.
Make server return the answer as that seems like a more likely and useful behavior than server only printing results to logs.

refactor: use `urllib` instead of `requests` in local code for sgl_vlm.py

---

06_gpu_and_ml/text-to-video/ltx.py

Explicitly moved the pipeline to the GPU, dropped the CPU offload, and set the dtype to bf16. This cuts inference time down substantially -- for a twenty second 480p video, can complete 10 steps in 2s or 100 steps in 20s.
Added the `--twice` flag/behavior we use in a few examples where we want to demonstrate the size of cold start latencies.
Reorganized the text a bit. Added more links to other Modal docs.
Removed the `download_model` function that didn't appear to be used. It's a good pattern, but we should put it in the model weights storage guide (also now linked in the example).

speed up ltx-video and reorganize text

---

misc/xgboost_optuna_search.py

This example shows how to Optuna & XGBoost for hyperparameter serach and Hyperband pruning. Some highlights:
1. Worker node communicates with the head node to decide if a trial should be pruned.
2. Uses async python to control the number of worker nodes.
3. Uses `max_containers=1` and `max_inputs=1000` for the head node, so that the dashboard stays up to date and there is only one container holding the study state.
4. Show how to quickly spin up the optuna dashboard:

Optuna & XGBoost for hyperparameter search and Hyperband pruning

---

06_gpu_and_ml/dreambooth/diffusers_lora_finetune.py

Some of the text and the app referred to the old `dreambooth` name. This updates the names to center LoRA, since that name has better branding.

fix and adjust naming in diffusers_lora_finetune

---

06_gpu_and_ml/stable_diffusion/flux.py

Noticed this when reading through the docs.

Fix typo in `flux.py`

---

05_scheduling/hackernews_alerts.py
06_gpu_and_ml/llm-structured/jsonformer_generate.py
06_gpu_and_ml/stable_diffusion/a1111_webui.py
07_web_endpoints/fastapi_app.py
07_web_endpoints/fasthtml-checkboxes/cbx_locustfile.py
07_web_endpoints/fasthtml-checkboxes/constants.py
07_web_endpoints/fastrtc_flip_webcam.py
07_web_endpoints/flask_app.py
08_advanced/poll_delayed_result.py
10_integrations/multion_news_agent.py
10_integrations/streamlit/app.py
10_integrations/tailscale/modal_tailscale.py
12_datasets/coco.py
12_datasets/imagenet.py
12_datasets/laion400.py
12_datasets/rosettafold.py
14_clusters/simple_torch_cluster_script.py
misc/hello_shebang.py
misc/say_hello_cron.py

Removes or documents all of the monitoring opt-outs. Those I fixed are very old opt-outs from when we couldn't do as much.
I used the following slugs to document reasons in YAML comments:
- `auxiliary-file`: this is an auxiliary Python file that's part of an example but not a monitored unit in its own right, like a script to be run from a Modal Function. This is the only good reason to skip monitoring, but it should still be used sparingly. A self-contained, self-documented application is a beautiful thing!
- `long-running`: this example runs for too long. These are all in `12_datasets`. We should rethink these examples in light of notebooks, cc @thundergolfer.
-  `deprecated`: this example should be removed. They're waiting on the deployment of a PR to `modal` …

resolve or document monitoring opt-outs

---

06_gpu_and_ml/comfyui/comfyclient.py
09_job_queues/doc_ocr_jobs.py

The comfyUI and OCR jobs examples both used `requests` in the local scope. Replacing with `urllib` equivalent to remove `requests` as a third-party dependency.

Replacing `requests` with `urllib` in comfy and ocr jobs examples

---

06_gpu_and_ml/text-to-audio/chatterbox_tts.py

Adds simple web endpoint example for running [Chatterbox TTS](https://github.com/resemble-ai/chatterbox) on Modal. I couldn't find a TTS example and Chatterbox was just released, is small, is fast, and has a simple client interface.

Adds Chatterbox TTS example

---

02_building_containers/install_flash_attn.py

Flash attn

---

06_gpu_and_ml/stable_diffusion/text_to_image.py

I was following the text-to-image example and noticed a URL was broken. I believe the one I have updated it to is correct since the topic is the same and since method ≈≈ function :~)

Fix broken link for CI documentation

---

05_scheduling/hackernews_alerts.py

The Hacker News example has a link that leads to a 404. Since the create secret link seems to depend on knowing the account ID, I've replaced it with instructions.

Fix broken 'create secret' link

---

06_gpu_and_ml/stable_diffusion/flux.py

The [FLUX blog post](https://modal.com/blog/flux-3x-faster) extends the FLUX example. Adding an update in the example that points to the blog.

Adding a link to the FLUX blog post in the FLUX example

---

06_gpu_and_ml/llm-serving/sgl_vlm.py

Update the SGLang VLM example to use volumes.

Update SGLang VLM example to use volumes

---

06_gpu_and_ml/stable_diffusion/image_to_image.py

Update the SDXL Turbo image to image example to use Flux Kontext.

Update sdxl turbo img-to-img eg to use flux kontext

---

06_gpu_and_ml/audio-editing/playdiffusion-model.py
06_gpu_and_ml/text-to-audio/chatterbox_tts.py

These two examples had lines like
`# #`
which produce an empty h1 tag that 1) was likely unintended and 2) triggers an a11y warning from the Svelte compiler (below).
The preferred style for representing whitespace in the examples is actually just a blank line -- they are ignored during frontend rendering but create a similar visual separation in the raw code files.

remove empty headers

---

06_gpu_and_ml/llm-serving/llama_cpp.py
06_gpu_and_ml/protein-folding/chai1.py

Screen readers use link text when announcing links, but in a few places we use a video as the link content, so screen readers don't know what to announce (at least until video understanding models are a few hundred times faster).
This PR adds the appropriate [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) attributes, which resolves a warning from the Svelte Compiler.

aria label for links around videos

---

06_gpu_and_ml/stable_diffusion/image_to_image.py

adds `object-fit` so that the image covers the whole 200x200 block and uses an ID to target in place of all divs

update css in img-to-img

---

06_gpu_and_ml/long-training.py

fix: .remote usage in long-running training guide no longer works

---

06_gpu_and_ml/long-training.py

for multinode training jobs, we observed a pretty nasty bug ([slack context](https://modal-com.slack.com/archives/C06US3ZTZMM/p1751493559578549?thread_ts=1751380622.240919&cid=C06US3ZTZMM)) where input cancellations are being ignored when running training as a subprocess. restricting `max_inputs=1` ensures that retried training runs are spawned on fresh containers. since we point multinode training users to this example to make their runs reentrant, seems like it deserved a shout out here.

add max_inputs=1 to long-training example

---

10_integrations/tailscale/modal_tailscale.py

Substitutes manual Dockerfile commands with `run_commands` and `entrypoint`.

Update Tailscale example to not use Dockerfile commands

---

10_integrations/tailscale/modal_tailscale.py

This guarantees that a configuration expected to happen only inside the container instead of applying them with `image.imports()`. This is better because imports might work locally, leading to the application of container-bound configurations locally.

Update Tailscale example to use `modal.is_local()`

---

06_gpu_and_ml/llm-serving/trtllm_latency.py

More recent versions of flashinfer-python fail to install in this example. This PR pins to the most recent working version.
Didn't root cause this one -- the install is looking for the CUDA runtime, which should be present (though the CUDA drivers are not, which might be the issue).
Error message below, for posterity.
```
× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [24 lines of output]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/tmp/pip-build-env-vak8231l/overlay/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing …
```

pins flashinfer version to one that installs properly

---

06_gpu_and_ml/llm-serving/trtllm_latency.py
06_gpu_and_ml/llm-serving/trtllm_throughput.py

This PR pins requests to the most recent working version compatible with the example. Root cause was figured out by looking at failing action logs.
```
Context:
=== Failed run 15853340643 ===
4T14:41:43.9000601Z   Attempting uninstall: huggingface_hub
2025-06-24T14:41:43.9001301Z     Found existing installation: huggingface-hub 0.33.0
2025-06-24T14:41:43.9454242Z     Uninstalling huggingface-hub-0.33.0:
2025-06-24T14:41:44.2624425Z       Successfully uninstalled huggingface-hub-0.33.0
2025-06-24T14:41:44.5025387Z 
2025-06-24T14:41:44.5307393Z Successfully installed hf-transfer-0.1.8 huggingface_hub-0.26.2 requests-2.31.0
2025-06-24T14:41:44.5310232Z ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of …
```

TRTLLM throughput version pin

---

06_gpu_and_ml/embeddings/text_embeddings_inference.py

Updating the outdated docker image. New images from [here](https://github.com/huggingface/text-embeddings-inference/pkgs/container/text-embeddings-inference)

APE-28: Fixing failures for text_embeddings_inference in fresh builds

---

07_web_endpoints/fasthtml-checkboxes/fasthtml_checkboxes.py

Dependency issue causing a crash loop in our deployment:
Error log:
```text
File "/usr/local/lib/python3.12/site-packages/fasthtml/common.py", line 7, in <module>
from sqlite_minutils import Database
ModuleNotFoundError: No module named 'sqlite_minutils'
```
Updated the fasthtml version to the latest one to fix it. Redeployed and tested.

Fix: example-checkbox crashlooping

---

06_gpu_and_ml/llm-serving/sgl_vlm.py

Updating the SGLang example to the latest version and updating the pinned dependencies. 

APE-28 Update the SGLang example to latest version

---

misc/trtllm_deepseek.py

Update PyTorch version from 2.7.0 to 2.7.1 to meet TensorRT-LLM 1.0.0rc0 requirements.
TensorRT-LLM 1.0.0rc0 requires PyTorch 2.7.1, so this change updates the PyTorch installation command to use the correct version for compatibility.

bump pytorch to 2.7.1 (required by trtllm 1.0.0rc0)

---

06_gpu_and_ml/gpu_snapshot.py

This still uses `_experimental_enable_gpu_snapshot`, but we can change that as soon as it's added to the client/server code.

add minimal GPU snapshot demo

---

06_gpu_and_ml/reinforcement-learning/grpo_trl.py
06_gpu_and_ml/reinforcement-learning/grpo_verl.py

Based on https://github.com/modal-labs/modal/pull/25104#issuecomment-3134080951

Update RL example names

---

06_gpu_and_ml/llm-serving/tokasaurus_throughput.py

Incorporate the comment's information into the prose.
Right now on https://modal.com/docs/examples/tokasaurus_throughput#configure-tokasaurus-for-maximum-throughput-on-this-workload, the comment looks like

fix: remove unused and unformatted Python comment

---

06_gpu_and_ml/audio-to-text/whisperx_transcribe.py
06_gpu_and_ml/comfyui/comfyapp.py
06_gpu_and_ml/dreambooth/diffusers_lora_finetune.py
06_gpu_and_ml/embeddings/image_embeddings_infinity.py
06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
06_gpu_and_ml/image-to-video/image_to_video.py
06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py
06_gpu_and_ml/llm-serving/tokasaurus_throughput.py
06_gpu_and_ml/llm-serving/vllm_inference.py
06_gpu_and_ml/obj_detection_webcam/webcam.py
06_gpu_and_ml/protein-folding/esm3.py
06_gpu_and_ml/reinforcement-learning/grpo_trl.py
06_gpu_and_ml/reinforcement-learning/grpo_verl.py
06_gpu_and_ml/reinforcement-learning/learn_math.py
06_gpu_and_ml/sam/segment_anything.py
06_gpu_and_ml/speech-to-text/batched_whisper.py
06_gpu_and_ml/text-to-audio/musicgen.py
06_gpu_and_ml/text-to-video/ltx.py
06_gpu_and_ml/text-to-video/mochi.py
06_gpu_and_ml/yolo/finetune_yolo.py
07_web_endpoints/webrtc/webrtc_yolo.py
misc/deepseek_openai_server.py
misc/flux_endpoint.py
misc/ollama_deployment.py

Adding a reference to our model weights on Modal guide in places we use it.
Also, fixed some "Modal weights" typos. Changed them to "model weights".
Checked the preview links for the changes to make sure no weight newline/formatting business.

Add guide for storing weights in places where we use volumes for model weights

---

06_gpu_and_ml/stable_diffusion/image_to_image.py

Remove unused `--strength` argument. [FluxKontextPipeline] doesn't seem to
accept a `strength` parameter.
Add `--output-path` argument.
```
modal run 06_gpu_and_ml/stable_diffusion/image_to_image.py \
--image-path 06_gpu_and_ml/stable_diffusion/demo_images/my-example.jpg \
--output-path /tmp/foo/bar.jpg \
--prompt 'Keep everything the same but change to be in the style of Frida Kahlo'
```
[FluxKontextPipeline]: https://github.com/huggingface/diffusers/blob/9d313fc718c8ace9a35f07dad9d5ce8018f8d216/docs/source/en/api/pipelines/flux.md#kontext

refactor: improve `image_to_image.py` entrypoint arguments

---

13_sandboxes/test_case_generator.py

⚡ Changes since last PR (https://github.com/modal-labs/modal-examples/pull/1280)
- Prompt Engineering - Tried a variety of different techniques - surprisingly,  the repetitive hints seem to be required for keeping the code working. I'll keep iterating a bit more but would prefer to keep this relatively error-free
- Sandbox Bells-and-Whistles: Added 2 tunnels - one for showing the code diff, one for [Allure](https://allurereport.org/) - cute testing report framework. See screenshots!
- SGLang: Made it the client-server model as [recommended](https://modal-com.slack.com/archives/C08G83NB9B3/p1753288465186799).
- Various cleanups + responded to comments 
‼️ Outstanding Issues
- Error is thrown with the final `asyncio.gather`, as the `.wait()` function throws an error on timeout. Will be …

Add Sandbox test case generator example - 2nd pass

---

13_sandboxes/test_case_generator.py

Test case generator example was being [flaky](https://modal-com.slack.com/archives/C044YUDC1QU/p1756857683821389). Further [inspection](https://github.com/user-attachments/files/22124146/output.txt) showed that the following line was throwing a JSONDecodeError ~25-50% of the time.
```python
output_contents = json.loads(output)["file_contents"]                                                                                                                                                                                                                               
```
This is due to the underlying model not outputting valid JSON, on occasion. Not ideal of course, but adding a try-catch. Could also catch the JSONDecodeError instead, but I'd also like to catch any errors where the JSON is …

Add error handling for test case gen

---

.github/workflows/preview-docs.yml

Context [here](https://modal-com.slack.com/archives/C044YUDC1QU/p1758553167055189). Failing run [here](https://github.com/modal-labs/modal-examples/actions/runs/17919363945). Working run [here](https://github.com/modal-labs/modal-examples/actions/runs/17919646099)
Afer the `-e modal_apps/docker_in_modal_tests` was added to `requirements.dev.txt` in the base modal repo, the working directory of the install is now relevant. Changed the CI command to enable this.

Fix preview docs CI: change working dir for requirements install

---

13_sandboxes/sandbox_pool.py

Limit `max_inputs` concurrency to 20 in Sandbox pool example
