03_scaling_out/youtube_face_detection.py
We might want to changes this to use YOLO or something better at some point (generalizing it to object detection)
=> Face detection example

09_job_queues/doc_ocr_frontend/app.jsx, 09_job_queues/doc_ocr_frontend/index.html, 09_job_queues/doc_ocr_jobs.py, 09_job_queues/doc_ocr_webapp.py
Updated the styling and added more screenshots:
=> Doc OCR example updates

08_advanced/parallel_execution.py, 08_advanced/poll_delayed_result.py
Needs a couple of small pending changes in the client lib, so awaiting those before merging this
=> Add examples of using FunctionCall handles for parallel execution and result polling

misc/batch_inference_using_huggingface.py
This triggers some issues with Modal right now, but we're working on it.
=> Batch inference using Huggingface

misc/batch_inference_using_huggingface.py
Clearing away the following warning:
=> Add <img/> alt tag to clear warning in frontend.

.github/workflows/check.yml, 03_scaling_out/youtube_face_detection.py, 06_gpu/mini_dalle_slackbot.py, 06_gpu/tensorflow_tutorial.py, 07_webhooks/chatbot_spa.py, 07_webhooks/fastapi_app.py, 08_advanced/parallel_execution.py, 08_advanced/poll_delayed_result.py, 09_job_queues/doc_ocr_jobs.py, 09_job_queues/doc_ocr_webapp.py, misc/algolia_indexer.py, misc/covid_datasette.py, misc/meltano.py, misc/sentence_embeddings.py
=> Add isort check

06_gpu/mini_dalle_slackbot.py, 06_gpu/tensorflow_tutorial.py, misc/algolia_indexer.py, misc/news_summarizer.py
I think this might fix a few failures we're seeing with synthetic monitors
=> Fix misc examples

02_building_containers/screenshot.py
I think previously we were just exercising this example with cold AWS Lambda functions.
=> fix: screenshot example can now run > 1times on same machine

03_scaling_out/fetch_stock_prices.py
Follow-up to https://github.com/modal-labs/modal-examples/pull/48. I should've kept reading down further 😅.
=> fix: handle empty prices in fetch_stock_prices pt2

03_scaling_out/nyc_taxi_matrix.py
Turns out this is already in Parquet and so it's ready to go!
=> Use DuckDB for the NYC taxi matrix

03_scaling_out/nyc_taxi_matrix.py
I'll rename it to something more apt (`duckdb_nyc_taxi_dataset.py` maybe) and will add some docs. Produces this:
=> NYC taxi example: Plot something more interesting

example_test.py, example_utils.py
https://twitter.com/coltonpadden/status/1581042285000929281
Is it easy to enable a broken link checker for our docs? Maybe worth it.
=> Fix Github links

misc/algolia_indexer.py
- Return a message from the webhook when it is completed
- Run the webhook in the default image instead of algolia
- Remove the `_crawl` function
=> Simplify the algolia indexer example

misc/vision_model_training.py
[You can just say _Gradio_.](https://getyarn.io/yarn-clip/ac15a40d-a48b-406b-b450-d06abd65236f)
=> nit: It's just 'Gradio'

misc/covid_datasette.py, misc/whisper_pod_transcriber/main.py
Adding now that default 5 min timeout is enforced.
=> Specify >5 min timeouts on fns that probably need it

misc/whisper_pod_transcriber/main.py
Brings in https://github.com/openai/whisper/pull/370 which reportedly offers huge speedups on CPU.
**Deployed with:** `modal app deploy whisper_pod_transcriber.main`
=> Update to latest openai/whisper, which has big CPU speedups

.github/workflows/cd.yml
Now the fun of merging changes in Github just to test your workflows 😞
=> fix: continuous deployment GH actions workflow

.github/workflows/cd.yml
Short-term fix.  We should add a proper `requirements.txt` soon.
=> fix: need jupytext in github actions

misc/gpt2_language_model.py
```
% python misc/gpt2_language_model.py "The best tool for deploying machine learning with Python"
[...]
The best tool for deploying machine learning with Python and Maven is the Machine Learning Toolkit, a cross-platform toolkit that enables you to use machine learning for large, complex 
organizations. This toolkit supports Python 2.7 and 4.x
```
=> GPT-2 example

misc/whisper_pod_transcriber/whisper_frontend/src/routes/episode.tsx, misc/whisper_pod_transcriber/whisper_frontend/src/routes/podcast.tsx
=> Fix footer placement on episode pages

06_gpu/stable_diffusion_slackbot.py
Also use `accelerate` and `fp16`.
=> Fix stable diffusion example

02_building_containers/import_sklearn.py, 03_scaling_out/basic_grid_search.py, misc/batch_inference_using_huggingface.py
See https://github.com/scikit-learn/sklearn-pypi-package — this was causing our image builds to sometimes break non-deterministically :')
=> Update sklearn images to use "scikit-learn" name

misc/covid_datasette.py, misc/vision_model_training.py, misc/webcam.py
cc @erikbern 
I will also delete the old apps from our org. (It's a minor bit of a deployment awkwardness that an app rename involves manual delete.)
=> Update example webhook URLs after 'example-' prefixing

misc/whisper_pod_transcriber/whisper_frontend/src/components/Footer.tsx, misc/whisper_pod_transcriber/whisper_frontend/src/routes/episode.tsx
Adds a bit more UI polish ✨. See video for what it looks like.
https://user-images.githubusercontent.com/12058921/202871172-7459c80d-7f86-45cd-93c0-e29a81b7131a.mp4
(39 second transcription!)
=> whisper transcript placeholder UI

README.md
=> README: explain folder structure of repo

misc/dreambooth_app.py
Fixes flake8 issues (Github refused to run these checks in the PR #104)
=> Flake8 for dreambooth

06_gpu/stable_diffusion_cli.py
The main changes:
* Instead of downloading a script and running it (during the image build phase), inline that script into the code itself
* Use container lifecycle hooks to load the model from disk
=> Misc updates to the fast stable diffusion

06_gpu/stable_diffusion_cli.py
Some of the docs from the original code was outdated.
=> Fix stable diffusion docs

06_gpu/stable_diffusion_cli.py
Together with a [raised cutoff for blob sizes](https://github.com/modal-labs/modal-client/pull/96), this takes the time per image down from  ~2.1s to ~1.6s (images that are returned seem to be a few hundred KB)
This should also make it possible to run the code without Pillow installed locally – I believe it would fail otherwise.
=> Convert to PNG in the container, return bytes

06_gpu/stable_diffusion_cli.py
There will be a warning about it, but it should be spurious.
=> Don't build image on A100s

06_gpu/stable_diffusion_cli.py
=> remove curl

01_getting_started/generators.py, 03_scaling_out/fetch_stock_prices.py, 08_advanced/generators_async.py, misc/google_search_generator.py
Otherwise there will be a deprecation warning (which triggers an error in the synthetic monitors)
=> use stub.function instead of stub.generator

06_gpu/tensorflow_tutorial.py
Our TF example has been failing for just over a week. These changes fix it for me when I run it locally.
=> fix: Conda + Tensorflow example

06_gpu/stable_diffusion_slackbot.py
See https://linear.app/modal-labs/issue/MOD-718/doc-generation-completely-skips-some-paragraphs
=> Temp fix for Stable Diffusion Slackbot docs

misc/dreambooth_app.py
- Uses Stable Diffusion 1.5 (I tried SD2, [made possible a few days ago](https://github.com/huggingface/diffusers/pull/1455), but the results were markably worse)
- Uses slightly better default parameters (did a bunch of manual experimentation because the initial default settings seemed to overfit)
- Uses `xformers` for ~10% faster inference 
- Fixes the link to the deployed app (retrained on the original Qwerty photos using new settings)
=> Dreambooth examples updates

ml/whisper_pod_transcriber/api.py, ml/whisper_pod_transcriber/main.py
Addressing this: 
>  Your deployment whisper-pod-transcriber scheduled a call of function `whisper_pod_transcriber.main.refresh_index` which failed.
and updating code for https://github.com/modal-labs/modal-client/pull/97. 
I think we have enough transcribed podcasts that 5 minutes wasn't enough for indexing. NBD
=> whisper: stop index build timing out; refresh code for github.com/modal-labs/modal-client/pull/97

01_getting_started/get_started.py, 01_getting_started/hello_world.py, 02_building_containers/import_sklearn.py, 02_building_containers/screenshot.py, 03_scaling_out/fetch_stock_prices.py, 03_scaling_out/youtube_face_detection.py, 04_secrets/db_to_sheet.py, 05_scheduling/hackernews_alerts.py, 06_gpu/import_torch.py, 06_gpu/mini_dalle_slackbot.py, 06_gpu/stable_diffusion_cli.py, 06_gpu/stable_diffusion_slackbot.py, 06_gpu/tensorflow_tutorial.py, 07_webhooks/chatbot_spa.py, 07_webhooks/count_faces.py, 08_advanced/hello_world_async.py, 08_advanced/parallel_execution.py, 08_advanced/poll_delayed_result.py, 09_job_queues/doc_ocr_jobs.py, 09_job_queues/doc_ocr_webapp.py, 10_integrations/duckdb_nyc_taxi.py
I also addressed some nits that I came across when running these examples just now. 
Next up is the larger examples in `data/` and `ml/`.
=> Update 1-10 examples code for github.com/modal-labs/modal-client/pull/97

data/covid_datasette.py, data/meltano/meltano_modal.py, data/pyjulia.py, data/pymc_pmf.py, misc/algolia_indexer.py, misc/batch_inference_using_huggingface.py, misc/dreambooth_app.py, misc/gpt2_language_model.py, misc/news_summarizer.py, misc/tqdm_progress_bar.py, misc/webcam.py, misc/webscraper.py, ml/text-to-pokemon/text_to_pokemon/api.py, ml/text-to-pokemon/text_to_pokemon/main.py, ml/text-to-pokemon/text_to_pokemon/ops.py, ml/vision_model_training.py
Updates `misc`, `ml`, and `data/`
The `kedro` integration in `integration/` looks a bit trickier, as it's tied into click CLI and looks to do runtime creation of modal funcs.
=> more api updates for https://github.com/modal-labs/modal-client/pull/97

01_getting_started/generators.py, 08_advanced/generators_async.py
A couple of missing API updates. Noticed by looking at synmon stats.
=> fix missed modal API updates

03_scaling_out/fetch_stock_prices.py, 06_gpu_and_ml/batch_inference_using_huggingface.py, 06_gpu_and_ml/mini_dalle_slackbot.py, 06_gpu_and_ml/stable_diffusion_cli.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/inpaint.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py, 06_gpu_and_ml/webcam.py, 10_integrations/stable_diffusion_slackbot.py
Direct follow-up to https://github.com/modal-labs/modal-examples/pull/139.
=> use context-manager form of BytesIO to get autoclose

06_gpu_and_ml/text-to-pokemon/tests/pokemon_naming_test.py, example_utils.py
Removing this since we're rendering a custom footer in the frontend instead.
=> Remove the github link

06_gpu_and_ml/dreambooth_app.py, 06_gpu_and_ml/mini_dalle_slackbot.py, 06_gpu_and_ml/stable_diffusion_cli.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py, 10_integrations/stable_diffusion_slackbot.py
https://www.nvidia.com/en-gb/data-center/products/a10-gpu/
=> Capitalize A10G correctly

03_scaling_out/basic_grid_search.py
Think I accidentally committed test code at some point
=> revert accidental commit with gpu

06_gpu_and_ml/dreambooth_app.py
Unlike conda as before, this one actually installs quickly and makes progress rather than constantly resolving.
Thanks @erikbern.
By the way, this doesn't fix the issue in beta-testing Slack, I have a minimal reproduction separate from this file.
=> Update dreambooth to also use debian_slim

06_gpu_and_ml/stable_diffusion_cli.py
I think this should make it work
=> Support Python 3.7

06_gpu_and_ml/text-to-pokemon/README.md, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/App.svelte, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/lib/components/Generator.svelte
=> fix: txt-to-Pokemon mobile styling

06_gpu_and_ml/text-to-pokemon/text_to_pokemon/frontend/src/lib/components/Generator.svelte
Had an unpushed commit on the branch.
=> fix: increase font-size of Share text

06_gpu_and_ml/stable_diffusion_cli.py
1. Use https://github.com/modal-labs/modal-client/pull/221 to install the latest xformers prerelase
2. Fix the `stub.run` inside `@local_entrypoint` (which actually was _working_, but i think added some extra latency)
=> Fix stable diffusion

06_gpu_and_ml/dreambooth_app.py
* Install latest `xformers` using `pip install --pre`
* Install the same version of diffusers as the train_dreambooth.py script
=> Fix dreambooth container image

06_gpu_and_ml/dreambooth_app.py
This requires https://github.com/modal-labs/modal-client/pull/222
=> Simplify Dreambooth entrypoint code

10_integrations/meltano/meltano_modal.py
Makes it a bit simpler to follow
=> Remove lifecycle class from meltano example

06_gpu_and_ml/dreambooth_app.py, 09_job_queues/doc_ocr_webapp.py
Need to change this first to make an internal PR build
=> Fix link to stubserve

06_gpu_and_ml/whisper_pod_transcriber/README.md, 06_gpu_and_ml/whisper_pod_transcriber/main.py
Cleaning up a bunch of entrypoints in the examples
=> use modal serve with whisper demo

07_webhooks/badges.py, 07_webhooks/chatbot_spa.py, 07_webhooks/flask_app.py, 08_advanced/poll_delayed_result.py, misc/say_hello_cron.py
removing it in a few more places
=> remove more stub.serve

10_integrations/covid_datasette.py
=> update covid datasette to use `modal serve`

03_scaling_out/fetch_stock_prices.py, 05_scheduling/schedule_simple.py, 06_gpu_and_ml/dreambooth_app.py, 06_gpu_and_ml/stable_diffusion_cli.py, 06_gpu_and_ml/tensorflow_tutorial.py, 06_gpu_and_ml/vision_model_training.py, 06_gpu_and_ml/webcam.py, 07_webhooks/badges.py, 07_webhooks/chatbot_spa.py, 07_webhooks/fastapi_app.py, 07_webhooks/flask_app.py, 08_advanced/generators_async.py, 08_advanced/hello_world_async.py, 08_advanced/parallel_execution.py, 08_advanced/poll_delayed_result.py, 09_job_queues/doc_ocr_jobs.py, 09_job_queues/doc_ocr_webapp.py, example_utils.py
* More local_entrypoints
* Added more metadata for running examples as synthetic monitors
=> Fix examples running as cli tools

06_gpu_and_ml/langchains/potus_speech_qanda.py
Demo based significantly off https://langchain.readthedocs.io/en/latest/modules/chains/combine_docs_examples/qa_with_sources.html
=> LangChain: basic working Q&A demo

06_gpu_and_ml/langchains/potus_speech_qanda.py
* ~Reformatting code to fit better within 80 chars~ Our `black` config doesn't like this.
* Fixing spelling and phrasing
* Refactoring the code as some parts looked rubbish in blog post form. eg:
=> Editing the 1st draft of the LangChain example

06_gpu_and_ml/langchains/potus_speech_qanda.py
=> Fix broken link to LangChain docs

03_scaling_out/basic_grid_search.py, 06_gpu_and_ml/dreambooth_app.py, 06_gpu_and_ml/vision_model_training.py, 06_gpu_and_ml/webcam.py, 07_webhooks/chatbot_spa.py, 09_job_queues/doc_ocr_webapp.py, 10_integrations/dbt/modal_dbt.py, 10_integrations/meltano/meltano_modal.py, example_test.py
This fixes all examples using the old `Mount` constructor
Also parametrizes the tests so it's easier to debug
=> fix mount constructor and parametrize pytests

10_integrations/algolia_indexer.py, 10_integrations/pyjulia.py, 10_integrations/pymc_pmf.py, 10_integrations/stable_diffusion_slackbot.py
Fixed two `if __name__ == "__main__":`
=> Fix some entrypoints

.github/workflows/cd.yml, example_test.py, example_utils.py
switches to pydantic for the internal class, also add a utility function to dump json
will use this for synthetic monitors + docs
=> compute cli_args, generate json

example_utils.py
needed both for monitors and examples
=> Add stem to internal struct

example_utils.py
=> use repo_filename in cmd args instead

06_gpu_and_ml/stable_diffusion_cli.py
The old one was a joke on Twitter from a while ago
=> Update the prompt

06_gpu_and_ml/langchains/potus_speech_qanda.py
1. If you create a new OpenAI account (thanks @gongy) our langchain example will fail with this: 
```RateLimitError: Rate limit reached for default-global-with-image-limits in organization org-FC8Ox38ZUwYawib30mWGgBmR on requests per min. Limit:
60.000000 / min. Current: 70.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to
increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
```
At least two users have tried the example and gotten this error now (one in beta testers, one in recent TreeHacks hackathon). 
2. Handle when the LLM provides un-processable sources/references: https://gist.github.com/Taytay/64c07c50ddfe920dc3a90626afc5b042.
**output:**
```
...
generating docsearch …
```
=> langchain example improvements

10_integrations/modal_tailscale.py
For accessing private networks via a userspace proxy
=> Adds example of setting up a tailscale sidecar

10_integrations/algolia_indexer.py
These configs are now in our public examples repo woo
=> Update algolia indexer params

06_gpu_and_ml/controlnet/demos.py
https://user-images.githubusercontent.com/12058921/222927911-3ab52dd1-f2ee-4fb8-97e8-dafbf96ed5c5.mp4
=> Add ControlNet demos web app

06_gpu_and_ml/langchains/potus_speech_qanda.py, 10_integrations/dbt/modal_dbt.py, 10_integrations/meltano/meltano_modal.py, 10_integrations/pymc_pmf.py, misc/news_summarizer.py
Reducing the amount of red that shows up in #synmon channel.
=> address example errors & flakiness

06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
After seeing it rendered on the website, noticed a few other things to fix or improve.
=> further improvements to controlnet demo script

06_gpu_and_ml/stable_diffusion_cli.py
=> [typo] Update stable_diffusion_cli.py

06_gpu_and_ml/alpaca/alpaca_lora.py
<kbd>
</kbd>
<br>-
**TODO**
Will leave the following as follow-up changes:
=> basic Alpaca LoRA example

.pre-commit-config.yaml
Running into the same issue as https://github.com/home-assistant/core/issues/86892
=> Bump pre-commit isort

06_gpu_and_ml/dreambooth_app.py
Separating it out so that the ASGI app runs in a CPU container. This makes the Gradio interface more responsive because we spin up more containers to handle concurrent requests (obviously not ideal that we need to do that, but that's how it is for now)
=> Separate inference function for Dreambooth example

06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py, 06_gpu_and_ml/whisper_pod_transcriber/pod_transcriber/main.py
Follow up to https://github.com/modal-labs/modal-examples/pull/266#discussion_r1157450348
=> clean up 2 uses of deprecated @stub.asgi

07_web_endpoints/badges.py, 07_web_endpoints/streaming.py
=> update outdated path in metadata

06_gpu_and_ml/alpaca/alpaca_lora.py, 06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/obj_detection_webcam/webcam.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_cli.py, 06_gpu_and_ml/vision_model_training.py
Uses the syntax merged in https://github.com/modal-labs/modal-client/pulls/400
=> Use `@cls` for lifecycle classes

06_gpu_and_ml/batch_inference/batch_inference_using_huggingface.py
It's failing CI over in https://github.com/modal-labs/modal-examples/pull/285
=> fix: batch inf example should use new lifecyle API

README.md
Another checklist item from the **modal-examples repo tune-up** document.
=> Add our logo to the README

03_scaling_out/basic_grid_search.py, 03_scaling_out/fetch_stock_prices.py, 03_scaling_out/youtube_face_detection.py
Following up on the Youtube example having ~50% reliability in the past few days. Seems PyTube has started being unreliable. There's about 5 issues about `KeyError: 'streamingData'` which is the error we're intermittently getting.
=> Youtube example reliability, and some maintenance

06_gpu_and_ml/stable_lm/main.py, internal/typecheck.py
Github actions didn't run on #284, possibly because @stanbiryukov is an outside contributor? 🤷
=> stability_lm CI nits

misc/gpt2_language_model.py
**Context:** https://modalbetatesters.slack.com/archives/C031Z7H15DG/p1682982880902289
=> Update GPT-2 example code

03_scaling_out/youtube_face_detection.py, 06_gpu_and_ml/openai_whisper/streaming/main.py
This fixed the whisper example for me when I ran it locally.
=> fix: PyTube 'main' is totally broken right now, awaiting PR merge

06_gpu_and_ml/openllama/openllama.py
Runs the 7B preview from https://github.com/openlm-research/open_llama.
=> OpenLLama on Modal

02_building_containers/screenshot.py, 03_scaling_out/youtube_face_detection.py, misc/webscraper.py
=> Fix some old examples

06_gpu_and_ml/openllama.py
This gets caught in the main repo, but not here :/
=> Fix broken link

06_gpu_and_ml/flan_t5/finetune.py
Example that demonstrates how to finetune Flan-T5 with monitoring Tensorboard.
=> finetune Flan-T5 with TensorBoard monitoring

03_scaling_out/fetch_stock_prices.py, 06_gpu_and_ml/falcon_bitsandbytes.py, 06_gpu_and_ml/flan_t5/finetune.py, 06_gpu_and_ml/mini_dalle_slackbot.py, 10_integrations/duckdb_nyc_taxi.py, misc/queue_simple.py, misc/webscraper.py
1. Fixing some failing examples
2. Opting a couple examples into `gVisor` experimental runtime.
=> Example reliability updates

03_scaling_out/youtube_face_detection.py, 06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/flan_t5/finetune.py, 06_gpu_and_ml/obj_detection_webcam/webcam.py, 06_gpu_and_ml/openai_whisper/finetuning/train/__main__.py, 06_gpu_and_ml/openai_whisper/finetuning/train/end_to_end_check.py, 06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py, 06_gpu_and_ml/spam-detect/spam_detect/app.py, 06_gpu_and_ml/tensorflow/tensorflow_tutorial.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/config.py, 06_gpu_and_ml/vision_model_training.py, 07_web_endpoints/chatbot_spa.py, 09_job_queues/doc_ocr_jobs.py, 10_integrations/covid_datasette.py, 10_integrations/dbt/modal_dbt.py, 10_integrations/kedro_modal/kedro_modal/modal_functions.py, 10_integrations/meltano/meltano_modal.py, 10_integrations/stable_diffusion_slackbot.py, 11_notebooks/jupyter_inside_modal.py, misc/news_summarizer.py
Replace constructor with `.new` and `().persist` with `.persisted`
=> Update to latest SharedVolume syntax

03_scaling_out/youtube_face_detection.py, 06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/flan_t5/finetune.py, 06_gpu_and_ml/obj_detection_webcam/webcam.py, 06_gpu_and_ml/openai_whisper/finetuning/train/__main__.py, 06_gpu_and_ml/openai_whisper/finetuning/train/end_to_end_check.py, 06_gpu_and_ml/openai_whisper/finetuning/train/transcribe.py, 06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py, 06_gpu_and_ml/openai_whisper/pod_transcriber/app/transcribe_check.py, 06_gpu_and_ml/spam-detect/spam_detect/app.py, 06_gpu_and_ml/spam-detect/spam_detect/model_registry.py, 06_gpu_and_ml/spam-detect/spam_detect/serving.py, 06_gpu_and_ml/spam-detect/spam_detect/train.py, 06_gpu_and_ml/tensorflow/tensorflow_tutorial.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/config.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/ops.py, 06_gpu_and_ml/vision_model_training.py, 07_web_endpoints/chatbot_spa.py, 09_job_queues/doc_ocr_jobs.py, 10_integrations/covid_datasette.py, 10_integrations/dbt/modal_dbt.py, 10_integrations/kedro_modal/kedro_modal/modal_functions.py, 10_integrations/meltano/meltano_modal.py, 10_integrations/stable_diffusion_slackbot.py, 11_notebooks/jupyter_inside_modal.py, misc/gpt2_language_model.py, misc/news_summarizer.py
This updates all examples to use the new class name.
=> SharedVolume -> NetworkFileSystem

06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/dreambooth/instance_example_urls.txt, 06_gpu_and_ml/falcon_bitsandbytes.py, 06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py, 06_gpu_and_ml/openllama.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_aitemplate.py, 09_job_queues/doc_ocr_jobs.py
Combing through and fixing examples.
=> fix: example reliability

10_integrations/dbt/modal_dbt.py, 10_integrations/meltano/meltano_modal.py
These have been broken for a while internally
=> Fix meltano and dbt synthetic monitor frontmatter

06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
Saw this linked by a beta user.
=> Update controlnet_gradio_demos.py for style

09_job_queues/doc_ocr_jobs.py
Stop implicitly encouraging this pattern. Favor `run_function`. There's 1 or 2 other examples I need to update.
=> update: stop using modal.NFS in OCR example

03_scaling_out/youtube_face_detection.py, 06_gpu_and_ml/obj_detection_webcam/webcam.py, 10_integrations/stable_diffusion_slackbot.py, misc/news_summarizer.py
=> Remove modal.NetworkFileSystem model loading usage (pt-2)

10_integrations/dbt/dbt_duckdb.py, 10_integrations/dbt/dbt_sqlite.py
=> fix DBT example metadata

06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/flan_t5/flan_t5_finetune.py
Draft pull request just to demonstration usage of beta `modal.Volume` feature as a replacement for `modal.NetworkFilesystem`.
=> [Draft] refactor modal.Volume into Dreambooth example

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py, 06_gpu_and_ml/tensorflow/tensorflow_tutorial.py, misc/queue_simple.py
=> fix: few example flakes in syn monitoring

07_web_endpoints/chatbot_spa.py
This is failing examples monitors too!
=> Update chatbot_spa.py with new stub syntax

03_scaling_out/youtube_face_detection.py
This fork taken from https://github.com/pytube/pytube/issues/1763
=> Fix pytube regex issue

10_integrations/algolia_indexer.py
Resolves MOD-902. cc @thundergolfer
=> Index top-level code blocks in algolia

02_building_containers/install_cuda.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_aitemplate.py, 06_gpu_and_ml/tensorflow/tensorflow_tutorial.py, 06_gpu_and_ml/text_generation_inference.py, 06_gpu_and_ml/vllm_inference.py, 10_integrations/algolia_indexer.py
https://github.com/modal-labs/modal-client/pull/794
=> Update examples to use from_registry

06_gpu_and_ml/text_generation_inference.py
=> Move TGI example to 2x80GB

06_gpu_and_ml/controlnet/controlnet_gradio_demos.py
Fixes https://github.com/modal-labs/modal-examples/issues/343
=> Pin python version in controlnet example

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py, 11_notebooks/basic.ipynb
=> fix: remove remaining usages of .call

06_gpu_and_ml/obj_detection_webcam/webcam.py
I'm guessing this is what it's supposed to be :)
=> Fixes typo in obj_detection_webcam comment

03_scaling_out/youtube_face_detection.py
This fixes the regex issue that hasn't been fixed in pytube yet, since they aren't maintaining the library.
=> Apply pytube patch to youtube_face_detection.py

06_gpu_and_ml/mlc_inference.py
=> Fix synthetic monitoring for mlc_inference

06_gpu_and_ml/spam-detect/spam_detect/serving.py
Update to syntax introduced in https://github.com/modal-labs/modal-client/pull/816
=> Use latest cls syntax

06_gpu_and_ml/dreambooth/dreambooth_app.py
=> fix deprecation warns; show logs from subprocess

06_gpu_and_ml/vision_model_training.py
Fix for deprecation error introduced in https://github.com/modal-labs/modal-client/pull/859
=> stub.app -> stub

06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/falcon_bitsandbytes.py, 06_gpu_and_ml/falcon_gptq.py, 06_gpu_and_ml/openllama.py
Will revert tomorrow when patch is out.
=> Pause running A100 examples on gvisor

06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py
=> Update dependencies in pod transcriber example

06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py
nice work putting up an sdxl example. i was just reading through and noticed this comment - updating it to be slightly more descriptive
=> sdxl torch compilation comment

misc/webscraper.py
https://modallabscommunity.slack.com/archives/C031Z7DBQFL/p1697833610325719
=> fix: webscraper image build

internal/utils.py
Currently, https://modal.com/docs/guide/ex/webscraper shows a slightly buggy layout.
This adds some text to the page when the entire example is just an example.
=> Fix webscraper example page

06_gpu_and_ml/diffusers/train_and_serve_diffusers_script.py
=> Fix CI / auto-format checker

02_building_containers/screenshot.py, 06_gpu_and_ml/alpaca/alpaca_lora.py, 06_gpu_and_ml/vision_model_training.py, 09_job_queues/doc_ocr_jobs.py, 10_integrations/dbt/dbt_sqlite.py, 10_integrations/streamlit/app.py, 10_integrations/streamlit/serve_app.py, README.md
=> Streamlit example

06_gpu_and_ml/embeddings/instructor.py
Mostly just boilerplate and the image
=> Add basic prompt-guided embedding example with instructor

06_gpu_and_ml/embeddings/text_embeddings_inference.py
Will annotate later and add to docs. Still have to measure token throughput and might have to add batching back to maximize it.
=> Add basic text-embeddings-inference example

06_gpu_and_ml/chatgpt/chatgpt_streaming.py, 06_gpu_and_ml/embeddings/instructor.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_turbo.py, 06_gpu_and_ml/stable_diffusion/stable_video_diffusion.py
Fix all the examples currently failing in synmon.
=> Example fixes (Dec 5)

06_gpu_and_ml/tgi_mixtral.py
=> fix: addr #527 model versioning issue

06_gpu_and_ml/dreambooth/dreambooth_app.py
Address #402 
This was already working in synmon, but we have a cached and old image.
=> version pinning dreambooth

03_scaling_out/youtube_face_detection.py
Not sure why we're deploying this example right now in synmon.
=> Don't deploy youtube_face_detection

06_gpu_and_ml/stable_diffusion/comfy_ui.py
Should have done this from the get-go.
=> Pin comfyui version in example for stability

06_gpu_and_ml/langchains/potus_speech_qanda.py
=> fix: deprecation err in langchain example

.github/workflows/check.yml
Fix issue with CI not running on #556
=> Update check.yml to run on external PRs

01_getting_started/generators.py
Support for this was dropped in client package version 0.57.0
=> Remove generator map() example

06_gpu_and_ml/text_generation_inference.py
Currently the deployed TGI example fails to return results. This was fixed by just bumping the model and image version; now cold start is only about 2 minutes.
=> update tgi model example

internal/utils.py
Perhaps isn't the most useful log line now.
> Ignoring examples files: ['/home/ubuntu/modal/examples/01_getting_started/__pycache__/generators.cpython-311.pyc', '/home/ubuntu/modal/examples/01_getting_started/__pycache__/hello_world.cpython-311.pyc', '/home/ubuntu/modal/examples/02_building_containers/__pycache__/import_sklearn.cpython-311.pyc', '/home/ubuntu/modal/examples/02_building_containers/urls.txt', '/home/ubuntu/modal/examples/06_gpu_and_ml/__pycache__/mini_dalle_slackbot.cpython-311.pyc', '/home/ubuntu/modal/examples/06_gpu_and_ml/__pycache__/mlc_inference.cpython-311.pyc', '/home/ubuntu/modal/examples/06_gpu_and_ml/blender/blender_dockerfile', '/home/ubuntu/modal/examples/06_gpu_and_ml/controlnet/demo_images', '/home/ubuntu/modal/examples/06_gpu_and_ml/dreambooth/__pycache__', …
=> Remove very long log line from get_examples()

.github/workflows/check.yml, .pre-commit-config.yaml, 06_gpu_and_ml/alpaca/alpaca_lora.py, 06_gpu_and_ml/spam-detect/spam_detect/app.py, 06_gpu_and_ml/stable_lm/stable_lm.py, internal/deploy.py, pyproject.toml
For consistency with the client package.
=> Update Ruff and remove Black

.github/pull_request_template.md
See #579 for an example of an issue that would've been avoided by someone following the more complete instructions here.
N/A
=> update versioning instructions on PR template

01_getting_started/hello_world.py
=> Updates to `hello_world` example

01_getting_started/hello_world.py
=> Fix relative paths in hello_world example

06_gpu_and_ml/llm-serving/text_generation_inference.py, 06_gpu_and_ml/llm-serving/tgi_mixtral.py, 06_gpu_and_ml/llm-serving/vllm_mixtral.py
`llm-frontend` and `llm-serving` are now in the same parent repo, which means the path reference has to be fixed
=> Fix llm frontend path for tgi mixtral

.github/workflows/check.yml, .pre-commit-config.yaml, 06_gpu_and_ml/openai_whisper/finetuning/train/__main__.py, 06_gpu_and_ml/spam-detect/spam_detect/models.py, 06_gpu_and_ml/tensorflow/tensorflow_tutorial.py, 06_gpu_and_ml/vision_model_training.py, 10_integrations/tailscale/modal_tailscale.py, internal/utils.py
=> updates tensorflow tutorial, pins version, drops conda

.github/workflows/cd.yml, .github/workflows/check.yml
Adds the ability to trigger our GitHub Actions from the UI or API
=> adds manual triggers for actions

06_gpu_and_ml/diffusers/train_and_serve_diffusers_script.py
=> fixes OOM error, volume bug, and environment issue in diffusers script example

06_gpu_and_ml/chatgpt/chatgpt_streaming.py
Example was old and outdated. 
=> Update chatGPT streaming example

06_gpu_and_ml/diffusers/train_and_serve_diffusers_script.py, 06_gpu_and_ml/dreambooth/dreambooth_app.py, 06_gpu_and_ml/embeddings/text_embeddings_inference.py, 06_gpu_and_ml/embeddings/wikipedia/download.py, 06_gpu_and_ml/embeddings/wikipedia/main.py, 06_gpu_and_ml/flan_t5/flan_t5_finetune.py, 06_gpu_and_ml/openai_whisper/finetuning/train/__main__.py, 06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py, 06_gpu_and_ml/spam-detect/spam_detect/app.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/config.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/main.py, 06_gpu_and_ml/text-to-pokemon/text_to_pokemon/ops.py, 06_gpu_and_ml/vision_model_training.py, 10_integrations/covid_datasette.py, 10_integrations/dbt/dbt_duckdb.py, 10_integrations/kedro_modal/kedro_modal/modal_functions.py
Update some examples:
1. Use `.from_name(..., create_if_missing=True)` instead of `.persisted(...)`
2. Use `Volume` instead of `NetworkFileSystem` to `Volume` if possible/easy
3. Remove use of stub assignments
Related to https://github.com/modal-labs/modal-client/pull/1466
=> Update a few examples

10_integrations/algolia_indexer.py
* Adjusted the ranking so that reference pages are not always at the bottom
* Fix indexing issue where there was blank data being shown for search results,
=> Fix relevance and indexing for Algolia search

06_gpu_and_ml/stable_diffusion/a1111_webui.py
=> simplifies a1111 example with webserver

06_gpu_and_ml/comfyui/comfy_ui.py, 06_gpu_and_ml/stable_diffusion/a1111_webui.py
=> Fix typos in comfyui / a1111 examples

06_gpu_and_ml/comfyui/workflow_api.py
=> make image name more dynamic

06_gpu_and_ml/stable_diffusion/a1111_webui.py
issue was reported and resolved by a user -- related to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9074
=> adds no-gradio-queue flag to avoid issue with long-running workflows

06_gpu_and_ml/langchains/codelangchain/README.md, 06_gpu_and_ml/langchains/codelangchain/app.py, 06_gpu_and_ml/langchains/codelangchain/common.py, 06_gpu_and_ml/langchains/codelangchain/retrieval.py, 06_gpu_and_ml/langchains/codelangchain/sandbox.py
=> adds a README and some docs to the codelangchain example

05_scheduling/schedule_simple.py
Sleep long enough that the per minute function gets to run at least once
=> Sleep longer in schedule_simple.py

internal/examples_test.py, internal/utils.py
Internal code. We can merge this after https://github.com/modal-labs/modal/pull/11778
=> Clean up get_examples()

06_gpu_and_ml/llm-serving/vllm_inference.py
A few updates to the base vLLM example:
- Use the `debian_slim` image instead of pulling the nvidia image from dockerhub, which we don't need for the example since the `vllm` Python package comes with cuda binaries
- Update the Mistral model to v0.2
- Use `run_function` kwargs instead of referring to global variables in direct contravention of the narrative text :) 
- Pin `transformers`
- Various small language and formatting tweaks
=> Several updates to the Mistral vLLM example

10_integrations/streamlit/serve_streamlit.py
- cmd in card should be `modal serve` not `modal run`
=> Update modal run with modal serve

06_gpu_and_ml/llm-serving/vllm_gemma.py, 06_gpu_and_ml/llm-serving/vllm_inference.py
Mostly updates to the `gemma` example, and a few more for the `mistral` one, aligning them after #691
=> Assorted improvements to vLLM inference examples

06_gpu_and_ml/llm-serving/vllm_mixtral.py
Follow-on to #691 in the Mixtral example. Mostly the same updates as there, but also some changes to the local entrypoint logic. Because we call `flush=True`, we were getting a single token on each line when we streamed the output into the terminal:
But if you remove `flush=True`, you don't get any streaming.
As a compromise, I am flushing every time a token ends with a newline. That still mostly gives you the "streaming" effect while keeping the text in the terminal readable.
=> Updates to mixtral vllm example

06_gpu_and_ml/llm-serving/text_generation_inference.py, 06_gpu_and_ml/llm-serving/tgi_mixtral.py, 06_gpu_and_ml/llm-serving/vllm_mixtral.py, 06_gpu_and_ml/stable_diffusion/playground.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_lightning.py, 10_integrations/cloud_bucket_mount_loras.py, 10_integrations/covid_datasette.py
Before merging https://github.com/modal-labs/modal-client/pull/1720
=> Rename functions named 'app' proactively

06_gpu_and_ml/llm-serving/tgi_mixtral.py
=> resolves mixtral gating issue on TGI example

06_gpu_and_ml/llm-serving/vllm_mixtral.py
Fix outdated example reference and update with current working code.
=> Update deploy and invoke section for vllm mixtral example

06_gpu_and_ml/llm-serving/trtllm_llama.py
TODO: go through the contributing checklist (version pinning, lambda/synmon testing)
TODO: view rendered in frontend, fix inevitable formatting bugs
=> adds TRT-LLM example

06_gpu_and_ml/blender/blender_video.py
=> resurrect blender

06_gpu_and_ml/openai_whisper/streaming/main.py
=> Fix whisper streaming

06_gpu_and_ml/comfyui/comfyapp.py
=> Fix some commas

06_gpu_and_ml/comfyui/helpers.py, 06_gpu_and_ml/comfyui/model.json
Add specific example / formatting for folks using custom nodes (based on user feedback).
=> add custom node example to comfyui

06_gpu_and_ml/comfyui/helpers.py
e.g. https://github.com/ssitu/ComfyUI_UltimateSDUpscale
Tested custom node above with this change and also the existing image resize custom node and both still work.
=> support comfyui plugins with submodules

06_gpu_and_ml/llm-serving/sgl_vlm.py
fixes regression where example would not build due to missing wheel dependency
=> explicitly install wheel dependency

11_notebooks/basic.ipynb
=> stub -> app

04_secrets/db_to_sheet.py
While fixing a missing secret issue in the monitoring environment, gave this old example a thorough read and added some points of clarification.
=> text edits and clarifications for db_to_sheet

06_gpu_and_ml/llm-serving/sgl_vlm.py
=> remove cuda devel image, move numpy downgrade earlier

03_scaling_out/basic_grid_search.py
=> Fix basic_grid_search.py

01_getting_started/hello_world.py
The document is written in a collaborative second-person plural, but "our computer" still scans to some readers as referring to Modal's infrastructure.
=> reword "our computer"

06_gpu_and_ml/comfyui/comfyapp.py
This happened to a user so just adding note here to remember to close ComfyUI tabs to avoid charges. Also linking to popular volume gist.
=> add warning about ui

06_gpu_and_ml/comfyui/comfyapp.py
Uses the latest "verified" ComfyUI commit sha. Seems to fix some intermittent issues running via api (at least locally).
=> update comfyui version

10_integrations/pushgateway.py
=> Add highlighting to concurrency limit in Pushgateway example

internal/readme.md
added some more info on top of what @pawalt added. thanks again for the writeup!
=> extend documentation of testing for examples

06_gpu_and_ml/flan_t5/flan_t5_finetune.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py
Helpfully reported by a user: https://modal-com.slack.com/archives/C06GPR10K9V/p1721588994774209
=> Fix broken link in Stable Diffusion XL

10_integrations/dbt/dbt_duckdb.py
=> Update out of date dbt example

06_gpu_and_ml/openai_whisper/batched_whisper.py
=> Batched whisper example nit

03_scaling_out/dynamic_batching.py
=> slight re-org

06_gpu_and_ml/stable_diffusion/stable_diffusion_cli.py
og sd 1.5 weights were taken down
=> point to fork of sd 1.5 weights

06_gpu_and_ml/llm-serving/vllm_gemma.py
=> Correct vllm_gemma.py filename in comment

08_advanced/code_interpreter.py
main change: added an `App` to the `Sandbox` since we're deprecating app-less Sandboxes.
=> update code_interpreter, minor text fixes, make testable

01_getting_started/generators.py, 05_scheduling/schedule_simple.py, 07_web_endpoints/count_faces.py, 07_web_endpoints/fastapi_app.py, 07_web_endpoints/fasthtml_app.py, 07_web_endpoints/flask_app.py, 07_web_endpoints/flask_streaming.py, 07_web_endpoints/streaming.py, 08_advanced/generators_async.py, 08_advanced/parallel_execution.py, 08_advanced/poll_delayed_result.py, 10_integrations/pyjulia.py, 10_integrations/webscraper.py, misc/lmdeploy_oai_compatible.py, misc/say_hello_cron.py, misc/stable_lm.py, misc/tgi_oai_compatible.py, misc/tqdm_progress_bar.py
- Add headers to non-ML examples that are missing them
=> Add headers to folders

06_gpu_and_ml/embeddings/instructor.py, 06_gpu_and_ml/embeddings/text_embeddings_inference.py, 06_gpu_and_ml/stable_diffusion/flux.py, 06_gpu_and_ml/stable_diffusion/playground.py, 06_gpu_and_ml/stable_diffusion/stable_diffusion_xl_lightning.py, 06_gpu_and_ml/stable_diffusion/stable_video_diffusion.py
Starting with the `06_gpu_and_ml` folder. The `spam_detect` and `text-to-pokemon` apps I'm not entirely sure what to do with
=> add headings to some ml examples

06_gpu_and_ml/gpu_fallbacks.py
[![asciinema recording](https://asciinema.org/a/KLTLdpKm56D41yofdVN2KXqWv.svg)](https://asciinema.org/a/KLTLdpKm56D41yofdVN2KXqWv)
=> add GPU fallback example

06_gpu_and_ml/stable_diffusion/flux.py
making this PR so we can run our CI on it
=> pulling in flux improvements from ShariqM fork

06_gpu_and_ml/long-training.py
in response to [this comment](https://github.com/modal-labs/modal-examples/pull/906#issuecomment-2390393921)
=> adds a code block demonstrating decorator pattern

06_gpu_and_ml/stable_diffusion/flux.py
we were missing the inductor baseline cache and FX_GRAPH_CACHE ([docs](https://pytorch.org/tutorials/recipes/torch_compile_caching_tutorial.html))
im seeing lower, but highly variable, compile times between ~90s and ~500s, shortened from 1100s
=> speed up torch compile with more cacheing

04_secrets/db_to_sheet.py
should now show up more cleanly if you search docs for postgres
=> more descriptive title for db_to_sheet

07_web_endpoints/count_faces.py
(likely still broken -- making a PR so I can run the CI async from other work on this repo)
=> bring back count_faces

06_gpu_and_ml/llm-serving/download_llama.py
=> Update download_llama.py to match vllm_inference.py

06_gpu_and_ml/comfyui/comfyapp.py
comfy-cli now support hf tokens: https://github.com/Comfy-Org/comfy-cli/pull/193
tested this with flux dev and works great.
=> add hf token instructions

internal/deploy.py
=> deploy as modules, rather than scripts, to support relative imports

10_integrations/covid_datasette.py
Optimize the `covid_datasette` example to have better "mechanical sympathy" with volumefs.
* Unpack report files in temp dir
* Preload report files
* Update db in temp dir
=> optimize covid_datasette

13_sandboxes/jupyter_sandbox.py, 13_sandboxes/safe_code_execution.py
Just some minor changes for cleaner rendering on the frontend
=> adjusts formatting of sandbox examples

06_gpu_and_ml/text-to-video/mochi.py
This PR adds early downloading of the T5 text encoder used by Mochi so that it doesn't need to be downloaded on each cold start.
=> faster mochi

10_integrations/algolia_indexer.py
Won't merge until we like the feel of it, but putting this PR out to show the changes. See: https://www.notion.so/modal-com/Minor-Docsearch-Improvements-1301e7f169498070babce860ef7f48f6?pvs=4
CC: @charlesfrye @ekzhang
=> Update Algolia Indexer

13_sandboxes/simple_code_interpreter.py
=> Clarify that code execution happens inside a container process

06_gpu_and_ml/llm-serving/trtllm_llama.py
https://asciinema.org/a/ooexWHsUBcd8XT3WrgxLKTpYf
=> Update TRT-LLM example, achieve 28k tok/s

.github/workflows/run-examples.yml, 04_secrets/db_to_sheet.py, 06_gpu_and_ml/dreambooth/diffusers_lora_finetune.py, 06_gpu_and_ml/embeddings/text_embeddings_inference.py, 06_gpu_and_ml/langchains/potus_speech_qanda.py, 06_gpu_and_ml/llm-serving/download_llama.py, 06_gpu_and_ml/llm-serving/trtllm_llama.py, 06_gpu_and_ml/llm-serving/vllm_inference.py, 06_gpu_and_ml/llm-structured/instructor_generate.py, 06_gpu_and_ml/obj_detection_webcam/webcam.py, 06_gpu_and_ml/yolo/finetune_yolo.py, 07_web_endpoints/fasthtml-checkboxes/cbx_load_test.py, 07_web_endpoints/fasthtml-checkboxes/fasthtml_checkboxes.py, 07_web_endpoints/streaming.py, 09_job_queues/doc_ocr_jobs.py, 09_job_queues/doc_ocr_webapp.py, 10_integrations/algolia_indexer.py, 10_integrations/cloud_bucket_mount_loras.py, 10_integrations/covid_datasette.py, 10_integrations/dbt/dbt_duckdb.py, 10_integrations/dbt_modal_inference/dbt_modal_inference.py, 10_integrations/pushgateway.py, 10_integrations/s3_bucket_mount.py, 10_integrations/streamlit/serve_streamlit.py, 10_integrations/webscraper.py, 12_datasets/laion400.py, 13_sandboxes/codelangchain/agent.py, 13_sandboxes/codelangchain/langserve.py, internal/run_example.py
This will need to be paired with a change to the monitoring sysyem to run examples in this environment by default as well.
=> switch default environment for examples in CI to 'examples'

06_gpu_and_ml/openai_whisper/batched_whisper.py
Dependency issue. Bumping everything.
Also some noisy formatting changes while I'm here.
=> fix librispeech download

06_gpu_and_ml/blender/blender_video.py
Setting the frame_skip parameter >1 during monitoring should also resolve the crashes that didn't reproduce elsewhere.
=> allow control of blender render from local client

.github/workflows/cd.yml, .github/workflows/check.yml, .github/workflows/preview-docs.yml, .github/workflows/run-examples.yml, .github/workflows/typecheck.yml
Makes all CI run on Ubuntu 24.04.
=> Accelerate 4 years into the future

06_gpu_and_ml/protein-folding/esm3.py
as picked up by synthetic monitoring, we are deprecating the Mount style and will instead use image methods with optional copies
=> update esm3 to new 'mount' style

07_web_endpoints/basic_web.py
This PR adds a section on the proxy auth feature to the `basic_web` example.
I tried pretty hard to improve on the sample shell command from the proxy auth guide but came up empty -- no combination of curl/wget flags or netrc settings avoided the need to base64 encode by hand.
=> add section on proxy authentication

14_clusters/simple_torch_cluster.py, 14_clusters/simple_torch_cluster_script.py
Most of the prose changes should be uncontroversial, but a quick technical gut check would be appreciated.
I added an argument to allow users to pass arguments to `torchrun`. Less about that being super useful and more about showing the pattern (which could be used to pass arguments to a script) and showing a bit of Modal's extra flexibility over other platforms.
The other code changes are cosmetic.
=> prose edits, lambda-test compat, and an extra argument

14_clusters/simple_torch_cluster.py
=> remove reference to CPU-only clusters

06_gpu_and_ml/llm-serving/llama_cpp.py
this is just as fast and much cheaper
=> h100s -> l40ses

06_gpu_and_ml/llm-serving/llama_cpp.py
=> Update title to include deepseek

misc/deepseek_openai_server.py
This PR introduces a FastAPI server integrated with the **DeepSeek-R1** model using the **llama.cpp** backend, optimized for high-performance, GPU-accelerated inference. The setup leverages **CUDA 12.4.0** and the full development toolkit to ensure efficient model execution. Key features include:
- **GPU-accelerated inference** utilizing 5x **NVIDIA L40S** GPUs for handling concurrent requests.
- **API key authentication** via the `X-API-Key` header to secure access.
- **Automatic model downloading** with persistent caching using **Modal Volumes** for seamless deployment.
- Support for **GGUF model file merging** to manage split model files efficiently.
- **Interactive API documentation** available through **Swagger UI** at `/docs`.
- **Configurable model parameters** such as:
- Context …
=> feat: Add FastAPI server for DeepSeek-R1 using llama.cpp

14_clusters/simple_torch_cluster.py
=> switch from shlex to varargs

06_gpu_and_ml/dreambooth/diffusers_lora_finetune.py, 06_gpu_and_ml/embeddings/text_embeddings_inference.py, 06_gpu_and_ml/embeddings/wikipedia/main.py, 06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py, 06_gpu_and_ml/llm-serving/trtllm_llama.py, 06_gpu_and_ml/llm-serving/vllm_inference.py, 06_gpu_and_ml/llm-structured/jsonformer_generate.py, 06_gpu_and_ml/llm-structured/outlines_generate.py, 06_gpu_and_ml/stable_diffusion/image_to_image.py, 06_gpu_and_ml/text-to-video/mochi.py, 06_gpu_and_ml/yolo/finetune_yolo.py, 14_clusters/simple_torch_cluster.py, misc/falcon_bitsandbytes.py, misc/falcon_gptq.py, misc/run_fooocus.py, misc/trellis3d.py
Planning to deprecate the classes in https://github.com/modal-labs/modal-client/pull/2848
=> Use strings for GPU config

06_gpu_and_ml/sam/segment_anything.py, 06_gpu_and_ml/stable_diffusion/flux.py, 06_gpu_and_ml/stable_diffusion/image_to_image.py, 06_gpu_and_ml/stable_diffusion/text_to_image.py, misc/trellis3d.py
See #1061 by @steve-marmalade. As an experiment, trying out re-opening the PR from a branch on our repo so that we can run our tests.
=> Fix hf hub cache env

06_gpu_and_ml/embeddings/qdrant.py
=> adds a minimal in-memory qdrant example

06_gpu_and_ml/llm-serving/trtllm_latency.py
=> add chat iface for trtllm latency example

06_gpu_and_ml/gpu_packing.py, 06_gpu_and_ml/yolo/finetune_yolo.py
=> move from deprecated __init__ to modal.parameter

06_gpu_and_ml/llm-serving/trtllm_latency.py
Also deploys the example, so that the simple chat client in the `__main__` block is always hitting the latest version.
=> update text to clarify relationship between batch and concurrency

07_web_endpoints/basic_web.py
=> Fix typo in web endpoint docs

06_gpu_and_ml/llm-serving/trtllm_latency.py
=> fix: small typos in `trtllm_latency.py`

06_gpu_and_ml/llm-serving/llama_cpp.py
=> fix: some type check warnings in llama_cpp.py

06_gpu_and_ml/llm-serving/chat_with_pdf_vision.py
=> fix: some typos and types in chat_with_pdf_vision.py

06_gpu_and_ml/text-to-video/ltx.py, 06_gpu_and_ml/text-to-video/mochi.py
=> add LTX text to video

06_gpu_and_ml/image-to-video/image_to_video.py, 06_gpu_and_ml/llm-serving/sgl_vlm.py, 06_gpu_and_ml/llm-serving/vllm_inference.py, 06_gpu_and_ml/stable_diffusion/text_to_image.py, 10_integrations/dbt_modal_inference/dbt_modal_inference.py, 10_integrations/pushgateway.py
Requires https://github.com/modal-labs/modal-client/pull/3088 to be merged first
=> Replace .web_url with .get_web_url

06_gpu_and_ml/embeddings/large_scale_embedding.py
=> Large Scale Embeddings Example Using Batch Processing

internal/readme.md
Remove some information that's not relevant, add some extra details.
=> update internal readme

internal/readme.md
This PR adds some extra material on workflows and processes for previewing the rendering of examples in the [documentation site](https://modal.com/docs).
=> adds section on frontend previews in internal README

internal/readme.md
=> clarify assumptions on directory structure

README.md
While also a good idea, this is also more of a test PR for some new GitHub configuration.
=> update logo link in readme from public-assets to modal-cdn

06_gpu_and_ml/hyperparameter-sweep/hp_sweep_gpt.py
Addressing #1186 
Adding a `VolumeMiddleware` from the [torch profiling example](https://github.com/modal-labs/modal-examples/blob/177d909525a8f2be6538ec638c3ef43aa54d6c70/06_gpu_and_ml/torch_profiling.py#L266-L283]) that reloads the Volume when the TensorBoard page is reloaded. 
=> Improve Volume reload performance in hp_sweep_gpt

06_gpu_and_ml/openai_whisper/pod_transcriber/app/api.py
Follow-up to https://github.com/modal-labs/modal-examples/pull/1183, had this in my local changes but forgot to push 🤦‍♂️
=> Remove outdated comment in podcast transcriber example

06_gpu_and_ml/tensorflow/tensorflow_tutorial.py
Another attempt to change tensorflow example to use volumes instead of NFS, using codes from https://github.com/modal-labs/modal-examples/issues/1186. History: https://github.com/modal-labs/modal-examples/pull/1184
=> Make tensorflow example use volumes

06_gpu_and_ml/image-to-video/image_to_video.py
Harmya tried to PR this in #1210, but CI won't run for external contributors.  
=> Inline the single-line helper function "slugify" in Image2video example

06_gpu_and_ml/llm-serving/trtllm_throughput.py, 06_gpu_and_ml/obj_detection_webcam/webcam.py, 06_gpu_and_ml/text-to-video/ltx.py, 10_integrations/cloud_bucket_mount_loras.py, 10_integrations/multion_news_agent.py
=> Fix broken links

06_gpu_and_ml/comfyui/comfyapp.py
=> update comfyUI and comfy-cli

06_gpu_and_ml/stable_diffusion/image_to_image.py
For the Flux Kontext image to image example, update the prompt and move to B200 gpu.
=> Flux Kontext: update prompt, move to b200

06_gpu_and_ml/stable_diffusion/image_to_image.py
center image for flux kontext eg
=> center img

06_gpu_and_ml/llm-serving/sgl_vlm.py
Fix model loading in SGLang VLM example.
=> Fix sglang vlm eg

06_gpu_and_ml/stable_diffusion/image_to_image.py
Remove fp8 version of Flux Kontext since it produces garbage:
=> Remove fp8 version of Flux Kontext

06_gpu_and_ml/embeddings/image_embeddings_infinity.py
=> fixed versions+renamed

06_gpu_and_ml/speech-to-text/streaming_kyutai_stt.py
Some small changes to the code as well, but nothing too big.
Still some work to do on this one, but IMO it's ready for the sidebar!
=> Add text for streaming kyutai STT example

06_gpu_and_ml/gpu_snapshot.py
Fix GPU snapshot example syntax.
=> Fix GPU snapshot example syntax

06_gpu_and_ml/llm-serving/tokasaurus_throughput.py, 06_gpu_and_ml/protein-folding/boltz_predict.py, 06_gpu_and_ml/protein-folding/chai1.py, 06_gpu_and_ml/stable_diffusion/image_to_image.py, misc/quic/quic_yolo_modal.py, misc/trtllm_deepseek.py
Switch all examples using uv to native uv_pip_install. All modified examples tested and working.
=> Switch all examples using uv to native uv_pip_install

06_gpu_and_ml/stable_diffusion/flux.py
=> fix: small typos in `flux.py`

06_gpu_and_ml/comfyui/comfyapp.py
--> https://github.com/modal-labs/modal-examples/pull/1328 to pass checks. Thanks @mmangkad for your contribution!
=> Update huggingface hub comfyapp version

06_gpu_and_ml/llm-serving/llama_cpp.py
A couple typos I found while working on another example
=> Fixing a few typos in llama_cpp

06_gpu_and_ml/gpu_snapshot.py
=> Add text to gpu snapshot example

06_gpu_and_ml/yolo/finetune_yolo.py
Recent [failed runs](https://modal-com.slack.com/archives/C044YUDC1QU/p1758499284807779) show that the underlying birds dataset was deleted or otherwise unavailable. Updated datasets.
Failing stacktrace from synmon:
`select stdout from "public"."metric" where metric='finetune_yolo' order by created_at desc limit 1;`
```
✓ Initialized. View run at 
https://modal.com/apps/modal-labs/examples/ap-CFECoef3XaS3yuJdCVBHo6
✓ Created objects.
├── 🔨 Created mount 
│   /var/task/modal-examples/06_gpu_and_ml/yolo/finetune_yolo.py
├── 🔨 Created function download_dataset.
├── 🔨 Created function train.
├── 🔨 Created function read_image.
└── 🔨 Created function Inference.*.
loading Roboflow workspace...
loading Roboflow workspace...
loading Roboflow project...
loading Roboflow project...
Traceback (most …
```
=> Update datasets for finetune yolo

06_gpu_and_ml/llm-serving/openai_compatible/load_test.py
Remote functions doesn't allow `Pathlib._local` module. This PR converts `csv_file` argument to string. 
**Error:**
```
modal.exception.DeserializationError: Deserialization failed because the 'pathlib._local' module is not available in the remote environment.
```
=> Fix csv_file argument type in load_test.py

09_job_queues/doc_ocr_jobs.py
=> Remove OCR frontend screenshot
